import Formal.ProfileSpace
import Formal.CausalProcess

/-!
# Attainable causal-policy profiles

`ProfileSpace.lean` proves the compact-order facts for the ambient cube
`ℕ → [0,1]`.  This module constructs the paper's actual causal subset.

For finite action and observation alphabets, a native test is a dependent
pair consisting of a horizon and a deterministic causal plan at that horizon.
These tests form a countably infinite type, so they admit an enumeration by
the natural numbers.  For a valid causal policy, the deficiency to any fixed
enumerated test is antitone along the policy's prefix experiment chain.  Its
infimum is therefore its limit and lies in `[0,1]`.

The raw attainable set is the range of this profile map and the completed
attainable set is its product-topology closure.  We prove that this closure is
nonempty and closed, hence compact; that its coordinate order is closed; that
every completed profile is dominated by a Pareto-minimal completed profile;
and that a policy has the zero profile exactly when it is natively sufficient.

No compactness or closedness of the raw policy space is assumed.  In
particular, membership of zero in the closure is deliberately kept distinct
from attainment of zero by one policy.
-/

namespace IdExp

open Filter Set Topology

set_option linter.unusedSectionVars false

/-- A finite deterministic native causal test: its horizon together with its
history-dependent deterministic action plan. -/
abbrev CausalNativeTest (A O : Type*) := Σ n : ℕ, CausalPlan A O n

variable {A O Θ : Type*} [Fintype A] [Fintype O]
  [Nonempty A] [Nonempty O] [Nonempty Θ]

/-- The native-test type is infinite because its horizon tag alone embeds the
natural numbers. -/
noncomputable instance causalNativeTestInfinite : Infinite (CausalNativeTest A O) :=
  Infinite.of_injective
    (fun n : ℕ => (⟨n, Classical.arbitrary (CausalPlan A O n)⟩ :
      CausalNativeTest A O))
    (fun _ _ h => congrArg (fun q : CausalNativeTest A O => q.1) h)

/-- A canonical, noncomputable enumeration of all finite native tests.  The
particular enumeration affects only coordinate names, not the product
topology or the zero-profile property. -/
noncomputable def causalNativeTestEnumeration : ℕ ≃ CausalNativeTest A O :=
  (Classical.choice
    (inferInstance : Nonempty (CausalNativeTest A O ≃ ℕ))).symm

/-- The observation experiment generated by one finite native test.  Actions
need not be repeated in its signal because the deterministic plan reconstructs
them from the observation word. -/
noncomputable def causalNativeTestExperiment
    (Qs : Θ → CausalResponse A O) (q : CausalNativeTest A O) :
    FiniteExperiment Θ (CausalObservationTrace O q.1) :=
  causalPlanObservationExperiment q.1 q.2 Qs

theorem causalNativeTestExperiment_valid
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (q : CausalNativeTest A O) :
    IsFiniteExperiment (causalNativeTestExperiment Qs q) := by
  rcases q with ⟨n, τ⟩
  exact causalPlanObservationExperiment_valid n τ Qs hQ

/-- Deficiency from the depth-`t` experiment collected by a policy to one
fixed native test. -/
noncomputable def causalPolicyTestDeficiency
    (π : ValidCausalPolicy A O) (Qs : Θ → CausalResponse A O)
    (q : CausalNativeTest A O) (t : ℕ) : ℝ :=
  finiteDeficiency
    (causalFiniteExperiment π.1 Qs t)
    (causalNativeTestExperiment Qs q)

/-- Directed deficiency between valid finite probability experiments is at
most one. -/
theorem finiteDeficiency_le_one_of_valid
    {X Y : Type*} [Fintype X] [Fintype Y] [Nonempty Y]
    (E : FiniteExperiment Θ X) (F : FiniteExperiment Θ Y)
    (hE : IsFiniteExperiment E) (hF : IsFiniteExperiment F) :
    finiteDeficiency E F ≤ 1 := by
  classical
  let y0 : Y := Classical.choice inferInstance
  let G : X → Y → ℝ := fun _ y => if y = y0 then 1 else 0
  have hG : G ∈ stochasticRules X Y := by
    intro x _
    constructor
    · intro y
      by_cases h : y = y0 <;> simp [G, h]
    · simp [G, y0]
  exact finiteDeficiency_le_of_decoder E F G hG 1
    (fun θ => decodeErr_le_one E F hE hF G hG θ)

/-- Later causal prefixes can only decrease deficiency to a fixed native
test.  This is the exact monotonicity needed for the limiting profile. -/
theorem causalPolicyTestDeficiency_antitone
    (π : ValidCausalPolicy A O)
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (q : CausalNativeTest A O) :
    Antitone (causalPolicyTestDeficiency π Qs q) := by
  intro s t hst
  calc
    causalPolicyTestDeficiency π Qs q t ≤
        finiteDeficiency
            (causalFiniteExperiment π.1 Qs t)
            (causalFiniteExperiment π.1 Qs s) +
          causalPolicyTestDeficiency π Qs q s :=
      finiteDeficiency_triangle
        (causalFiniteExperiment π.1 Qs t)
        (causalFiniteExperiment π.1 Qs s)
        (causalNativeTestExperiment Qs q)
        (causalFiniteExperiment_valid π.1 π.2 Qs hQ t)
        (causalFiniteExperiment_valid π.1 π.2 Qs hQ s)
        (causalNativeTestExperiment_valid Qs hQ q)
    _ = causalPolicyTestDeficiency π Qs q s := by
      rw [finiteDeficiency_causalPrefix_eq_zero π.1 π.2 Qs hQ hst]
      simp

/-- The limiting deficiency coordinate, represented by the infimum of the
antitone prefix deficiencies. -/
noncomputable def causalPolicyProfileValue
    (π : ValidCausalPolicy A O) (Qs : Θ → CausalResponse A O)
    (e : ℕ ≃ CausalNativeTest A O) (j : ℕ) : ℝ :=
  sInf (Set.range (causalPolicyTestDeficiency π Qs (e j)))

theorem causalPolicyProfileValue_nonneg
    (π : ValidCausalPolicy A O)
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) (j : ℕ) :
    0 ≤ causalPolicyProfileValue π Qs e j := by
  unfold causalPolicyProfileValue
  apply le_csInf (Set.range_nonempty _)
  rintro d ⟨t, rfl⟩
  exact finiteDeficiency_nonneg_of_valid
    (causalFiniteExperiment π.1 Qs t)
    (causalNativeTestExperiment Qs (e j))
    (causalFiniteExperiment_valid π.1 π.2 Qs hQ t)
    (causalNativeTestExperiment_valid Qs hQ (e j))

theorem causalPolicyProfileValue_le_one
    (π : ValidCausalPolicy A O)
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) (j : ℕ) :
    causalPolicyProfileValue π Qs e j ≤ 1 := by
  let f : ℕ → ℝ := causalPolicyTestDeficiency π Qs (e j)
  have hbdd : BddBelow (Set.range f) := by
    refine ⟨0, ?_⟩
    rintro d ⟨t, rfl⟩
    exact finiteDeficiency_nonneg_of_valid
      (causalFiniteExperiment π.1 Qs t)
      (causalNativeTestExperiment Qs (e j))
      (causalFiniteExperiment_valid π.1 π.2 Qs hQ t)
      (causalNativeTestExperiment_valid Qs hQ (e j))
  calc
    causalPolicyProfileValue π Qs e j = sInf (Set.range f) := rfl
    _ ≤ f 0 := csInf_le hbdd ⟨0, rfl⟩
    _ ≤ 1 := finiteDeficiency_le_one_of_valid
      (causalFiniteExperiment π.1 Qs 0)
      (causalNativeTestExperiment Qs (e j))
      (causalFiniteExperiment_valid π.1 π.2 Qs hQ 0)
      (causalNativeTestExperiment_valid Qs hQ (e j))

/-- The policy's concrete point in the profile cube. -/
noncomputable def causalPolicyProfile
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O)
    (π : ValidCausalPolicy A O) : ProfileCube :=
  fun j => ⟨causalPolicyProfileValue π Qs e j,
    causalPolicyProfileValue_nonneg π Qs hQ e j,
    causalPolicyProfileValue_le_one π Qs hQ e j⟩

@[simp]
theorem causalPolicyProfile_coe
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O)
    (π : ValidCausalPolicy A O) (j : ℕ) :
    ((causalPolicyProfile Qs hQ e π j : Set.Icc (0 : ℝ) 1) : ℝ) =
      causalPolicyProfileValue π Qs e j := rfl

/-- Each profile coordinate is not merely an infimum: it is the actual limit
of the antitone finite-prefix deficiencies. -/
theorem causalPolicyProfileValue_tendsto
    (π : ValidCausalPolicy A O)
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) (j : ℕ) :
    Tendsto (causalPolicyTestDeficiency π Qs (e j)) atTop
      (𝓝 (causalPolicyProfileValue π Qs e j)) := by
  let f : ℕ → ℝ := causalPolicyTestDeficiency π Qs (e j)
  have hanti : Antitone f := causalPolicyTestDeficiency_antitone π Qs hQ (e j)
  have hbdd : BddBelow (f '' Ici 0) := by
    refine ⟨0, ?_⟩
    rintro d ⟨t, _, rfl⟩
    exact finiteDeficiency_nonneg_of_valid
      (causalFiniteExperiment π.1 Qs t)
      (causalNativeTestExperiment Qs (e j))
      (causalFiniteExperiment_valid π.1 π.2 Qs hQ t)
      (causalNativeTestExperiment_valid Qs hQ (e j))
  have ht := Real.tendsto_atTop_csInf_of_antitoneOn_bddBelow_nat_Ici
    (hanti.antitoneOn (Ici 0)) hbdd
  have himage : f '' Ici 0 = Set.range f := by
    ext x
    simp
  rw [himage] at ht
  simpa [causalPolicyProfileValue, f] using ht

/-- Zero profile implies simultaneous finite-depth native sufficiency because
the test family at each fixed depth is finite. -/
theorem causalPolicyProfile_eq_zeroProfile_iff_nativelySufficient
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O)
    (π : ValidCausalPolicy A O) :
    causalPolicyProfile Qs hQ e π = zeroProfile ↔
      CausalNativelySufficient Qs π := by
  constructor
  · intro hzero n ε hε
    classical
    have htest : ∀ τ : CausalPlan A O n,
        ∃ T, causalPolicyTestDeficiency π Qs ⟨n, τ⟩ T < ε := by
      intro τ
      let j : ℕ := e.symm ⟨n, τ⟩
      have hcoord := congrArg
        (fun p : ProfileCube => ((p j : Set.Icc (0 : ℝ) 1) : ℝ)) hzero
      have hinf : causalPolicyProfileValue π Qs e j = 0 := by
        simpa [zeroProfile] using hcoord
      have hlt : causalPolicyProfileValue π Qs e j < ε := hinf.symm ▸ hε
      obtain ⟨d, ⟨T, hT⟩, hd⟩ := exists_lt_of_csInf_lt
        (Set.range_nonempty (causalPolicyTestDeficiency π Qs (e j)))
        (by simpa [causalPolicyProfileValue] using hlt)
      refine ⟨T, ?_⟩
      have hej : e j = (⟨n, τ⟩ : CausalNativeTest A O) := e.apply_symm_apply _
      have hdT : causalPolicyTestDeficiency π Qs (e j) T < ε :=
        hT.trans_lt hd
      simpa [hej] using hdT
    choose cutoff hcutoff using htest
    refine ⟨∑ τ, cutoff τ, ?_⟩
    intro t ht τ
    have hτsum : cutoff τ ≤ ∑ q, cutoff q :=
      Finset.single_le_sum (fun _ _ => Nat.zero_le _) (Finset.mem_univ τ)
    exact (causalPolicyTestDeficiency_antitone π Qs hQ ⟨n, τ⟩
      (hτsum.trans ht)).trans_lt (hcutoff τ)
  · intro hnative
    apply funext
    intro j
    apply Subtype.ext
    change causalPolicyProfileValue π Qs e j = 0
    have hnonneg := causalPolicyProfileValue_nonneg π Qs hQ e j
    apply le_antisymm
    · apply le_of_forall_pos_le_add
      intro ε hε
      obtain ⟨T, hT⟩ := hnative (e j).1 ε hε
      let f : ℕ → ℝ := causalPolicyTestDeficiency π Qs (e j)
      have hbdd : BddBelow (Set.range f) := by
        refine ⟨0, ?_⟩
        rintro d ⟨t, rfl⟩
        exact finiteDeficiency_nonneg_of_valid
          (causalFiniteExperiment π.1 Qs t)
          (causalNativeTestExperiment Qs (e j))
          (causalFiniteExperiment_valid π.1 π.2 Qs hQ t)
          (causalNativeTestExperiment_valid Qs hQ (e j))
      have hle : causalPolicyProfileValue π Qs e j ≤ f T := by
        exact csInf_le hbdd ⟨T, rfl⟩
      simpa using hle.trans (hT T le_rfl (e j).2).le
    · exact hnonneg

/-- Raw profiles attained by individual valid causal policies. -/
def causalPolicyProfiles
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) : Set ProfileCube :=
  Set.range (causalPolicyProfile Qs hQ e)

/-- The paper's completed attainable profile set: product-topology closure of
the raw causal-policy profiles. -/
def causalProfileClosure
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) : Set ProfileCube :=
  closure (causalPolicyProfiles Qs hQ e)

theorem causalProfileClosure_isClosed
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) :
    IsClosed (causalProfileClosure Qs hQ e) :=
  isClosed_closure

/-- One explicit valid policy, used only to witness nonemptiness of the raw
and completed profile sets. -/
noncomputable def defaultValidCausalPolicy : ValidCausalPolicy A O := by
  let τ : CausalPlan A O 0 := Classical.arbitrary _
  exact ⟨causalPolicyOfPlan 0 τ, isCausalPolicy_causalPolicyOfPlan 0 τ⟩

theorem causalPolicyProfiles_nonempty
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) :
    (causalPolicyProfiles Qs hQ e).Nonempty :=
  ⟨causalPolicyProfile Qs hQ e defaultValidCausalPolicy,
    ⟨defaultValidCausalPolicy, rfl⟩⟩

theorem causalProfileClosure_nonempty
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) :
    (causalProfileClosure Qs hQ e).Nonempty :=
  (causalPolicyProfiles_nonempty Qs hQ e).mono subset_closure

/-- The completed attainable profile space as an honest subtype of the
ambient cube. -/
abbrev CausalProfileCompletion
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) :=
  {p : ProfileCube // p ∈ causalProfileClosure Qs hQ e}

noncomputable instance causalProfileCompletionNonempty
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) :
    Nonempty (CausalProfileCompletion Qs hQ e) :=
  ⟨⟨Classical.choose (causalProfileClosure_nonempty Qs hQ e),
    Classical.choose_spec (causalProfileClosure_nonempty Qs hQ e)⟩⟩

instance causalProfileCompletionCompactSpace
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) :
    CompactSpace (CausalProfileCompletion Qs hQ e) :=
  isCompact_iff_compactSpace.mp (causalProfileClosure_isClosed Qs hQ e).isCompact

/-- Closedness of the capability order after restriction to the actual
completed causal profile set. -/
theorem isClosed_causalProfileOrder
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) :
    IsClosed {pq : CausalProfileCompletion Qs hQ e ×
        CausalProfileCompletion Qs hQ e | pq.1 ≤ pq.2} := by
  let valPair : CausalProfileCompletion Qs hQ e ×
      CausalProfileCompletion Qs hQ e → ProfileCube × ProfileCube :=
    fun pq => (pq.1.1, pq.2.1)
  have hpre : {pq : CausalProfileCompletion Qs hQ e ×
      CausalProfileCompletion Qs hQ e | pq.1 ≤ pq.2} =
      valPair ⁻¹' {pq : ProfileCube × ProfileCube | pq.1 ≤ pq.2} := by
    ext pq
    rfl
  rw [hpre]
  exact isClosed_profileOrder.preimage (by fun_prop)

/-- Pareto-minimal points of the completed deficiency set; these are the
paper's Pareto-admissible capability profiles because smaller deficiency is
more capable. -/
def causalParetoFrontier
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) : Set ProfileCube :=
  {m | m ∈ causalProfileClosure Qs hQ e ∧
    ∀ q ∈ causalProfileClosure Qs hQ e, q ≤ m → m ≤ q}

/-- Every completed causal profile is dominated by a Pareto-admissible
completed profile. -/
theorem exists_pareto_causalProfile
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O)
    {p : ProfileCube} (hp : p ∈ causalProfileClosure Qs hQ e) :
    ∃ m ∈ causalParetoFrontier Qs hQ e, m ≤ p := by
  obtain ⟨m, hm, hmp, hmin⟩ :=
    exists_pareto_profile (causalProfileClosure_isClosed Qs hQ e) hp
  exact ⟨m, ⟨hm, hmin⟩, hmp⟩

theorem causalParetoFrontier_nonempty
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) :
    (causalParetoFrontier Qs hQ e).Nonempty := by
  obtain ⟨p, hp⟩ := causalProfileClosure_nonempty Qs hQ e
  obtain ⟨m, hm, _⟩ := exists_pareto_causalProfile Qs hQ e hp
  exact ⟨m, hm⟩

/-- If zero belongs to the completed causal profile set, it is its unique
Pareto-frontier point.  This does not assert that a policy attains it. -/
theorem causalParetoFrontier_eq_singleton_of_zero_mem
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O)
    (hz : zeroProfile ∈ causalProfileClosure Qs hQ e) :
    causalParetoFrontier Qs hQ e = {zeroProfile} := by
  ext m
  constructor
  · rintro ⟨hm, hmin⟩
    exact Set.mem_singleton_iff.mpr
      (eq_zeroProfile_of_minimal hz hm hmin)
  · intro hm
    have hm0 : m = zeroProfile := Set.mem_singleton_iff.mp hm
    subst m
    refine ⟨hz, ?_⟩
    intro q hq hq0
    exact zeroProfile_le q

/-- A policy attains zero exactly when it is natively sufficient. -/
theorem zeroProfile_mem_causalPolicyProfiles_iff
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O) :
    zeroProfile ∈ causalPolicyProfiles Qs hQ e ↔
      ∃ π : ValidCausalPolicy A O, CausalNativelySufficient Qs π := by
  constructor
  · rintro ⟨π, hπ⟩
    exact ⟨π,
      (causalPolicyProfile_eq_zeroProfile_iff_nativelySufficient
        Qs hQ e π).mp hπ⟩
  · rintro ⟨π, hπ⟩
    exact ⟨π,
      (causalPolicyProfile_eq_zeroProfile_iff_nativelySufficient
        Qs hQ e π).mpr hπ⟩

end IdExp
