import Formal.CausalExperiment
import Formal.CausalProcess
import Formal.DominatedPrefix

/-!
# Finite-class prefix continuity on the causal path space

**Relevance:** direct current-paper support for `prop:l1-prefix` (finite-class
specialization) and the finite-prefix half of `thm:finite-recovery` in
`Paper/draft/main.tex`.

`DominatedPrefix.lean` proves prefix continuity for an abstract filtration on
an abstract standard-Borel space, with the prefix experiment encoded as the
trimmed coarse-sigma-algebra experiment `(Ω, ℱ t)`.  This module instantiates
that theorem on the paper's causal path space `CausalTraj A O = ℕ → A × O`:

* `causalPrefixMap t` is the length-`t` prefix map onto the explicit finite
  trace space `CausalFiniteTrace A O t = Fin t → A × O`, and
  `causalTraceSection t` is a measurable right inverse;
* `causalPrefixSigma A O t` is the sigma-algebra generated by the prefix map;
  the bundled `causalPrefixFiltration A O` is a filtration whose supremum is
  the product sigma-algebra (`iSup_causalPrefixFiltration`);
* `causalPathExperiment` is the complete path experiment `K_{π,∞}` and
  `causalTraceMeasureExperiment` is the pushforward `K_{π,t}` under the prefix
  map; its singleton masses are exactly the paper's finite trace experiment
  `causalFiniteExperiment` (`causalTraceMeasureExperiment_singleton`);
* `causalTrim_eq_map` identifies the trimmed coarse experiment with the
  pushforward of the trace measure along the section, so the two encodings
  are exact deterministic garblings of each other
  (`trimFinite_causalPath_eq_decode`, `causalTraceMeasureExperiment_eq_decode_trim`),
  and consequently have the same directed deficiency to every target
  (`finiteMeasureDeficiency_trace_eq_trim`);
* for a nonempty finite class the path laws are dominated by their sum, the
  Radon–Nikodym densities form a finite (hence relatively compact) family in
  `L¹`, and `tendsto_causalTrimPrefixDeficiency` /
  `tendsto_causalPrefixDeficiency` are the resulting prefix continuity
  `δ(K_{π,t}, K_{π,∞}) → 0` in trimmed and explicit-trace form, together with
  the displayed `(1/2)·max_θ ‖E[f_θ | ℱ_t] − f_θ‖_{L¹(P̄)}` bound
  (`causalTrimPrefixDeficiency_le_half_max_L1`,
  `causalPrefixDeficiency_le_half_max_L1`).

The dominating mixture is the unnormalized sum `P̄ = ∑_θ P_θ`; the paper's
display uses the uniform mixture and the densities `ρ = f / m`, which gives
the same bound after rescaling.
-/

set_option linter.unusedSectionVars false

namespace IdExp

open MeasureTheory ProbabilityTheory Filter Topology
open scoped ENNReal

variable {A O Θ : Type*} [Fintype A] [Fintype O]
  [MeasurableSpace A] [MeasurableSpace O]
  [MeasurableSingletonClass A] [MeasurableSingletonClass O]

/-! ## The prefix map and its section -/

/-- The length-`t` prefix of an infinite causal path. -/
def causalPrefixMap (t : ℕ) : CausalTraj A O → CausalFiniteTrace A O t :=
  fun ω k => ω k.1

theorem causalPrefixMap_apply (t : ℕ) (ω : CausalTraj A O) (k : Fin t) :
    causalPrefixMap t ω k = ω k.1 := rfl

theorem measurable_causalPrefixMap (t : ℕ) :
    Measurable (causalPrefixMap (A := A) (O := O) t) :=
  measurable_pi_lambda _ fun k => measurable_pi_apply k.1

/-- Restricting a length-`t` trace to its first `s ≤ t` coordinates. -/
def causalTraceRestrict {s t : ℕ} (hst : s ≤ t) :
    CausalFiniteTrace A O t → CausalFiniteTrace A O s :=
  fun w k => w (Fin.castLE hst k)

theorem measurable_causalTraceRestrict {s t : ℕ} (hst : s ≤ t) :
    Measurable (causalTraceRestrict (A := A) (O := O) hst) :=
  measurable_pi_lambda _ fun k => measurable_pi_apply (Fin.castLE hst k)

theorem causalTraceRestrict_comp_causalPrefixMap {s t : ℕ} (hst : s ≤ t) :
    causalTraceRestrict hst ∘ causalPrefixMap (A := A) (O := O) t =
      causalPrefixMap s := by
  funext ω k
  rfl

/-- The preimage of a single finite trace under the prefix map is the exact
cylinder of that trace. -/
theorem causalPrefixMap_preimage_singleton (t : ℕ) (w : CausalFiniteTrace A O t) :
    causalPrefixMap t ⁻¹' {w} = causalCyl (List.ofFn w) := by
  ext ω
  rw [Set.mem_preimage, Set.mem_singleton_iff, mem_causalCyl_ofFn, funext_iff]
  rfl

/-- A measurable right inverse of the prefix map: extend a finite trace by a
fixed action-observation pair. -/
noncomputable def causalTraceSection [Nonempty A] [Nonempty O] (t : ℕ) :
    CausalFiniteTrace A O t → CausalTraj A O :=
  fun w k => if h : k < t then w ⟨k, h⟩ else Classical.arbitrary (A × O)

theorem causalPrefixMap_causalTraceSection [Nonempty A] [Nonempty O] (t : ℕ)
    (w : CausalFiniteTrace A O t) :
    causalPrefixMap t (causalTraceSection t w) = w := by
  funext k
  simp [causalPrefixMap, causalTraceSection, k.2]

theorem causalPrefixMap_comp_causalTraceSection [Nonempty A] [Nonempty O] (t : ℕ) :
    causalPrefixMap t ∘ causalTraceSection (A := A) (O := O) t = id := by
  funext w
  exact causalPrefixMap_causalTraceSection t w

theorem measurable_causalTraceSection [Nonempty A] [Nonempty O] (t : ℕ) :
    Measurable (causalTraceSection (A := A) (O := O) t) :=
  measurable_of_countable _

/-! ## The prefix filtration -/

set_option warn.classDefReducibility false in
/-- Events determined by the length-`t` prefix of the path. -/
def causalPrefixSigma (A O : Type*) [Fintype A] [Fintype O]
    [MeasurableSpace A] [MeasurableSpace O]
    [MeasurableSingletonClass A] [MeasurableSingletonClass O] (t : ℕ) :
    MeasurableSpace (CausalTraj A O) :=
  MeasurableSpace.comap (causalPrefixMap t) inferInstance

theorem causalPrefixSigma_le (t : ℕ) :
    causalPrefixSigma A O t ≤ (inferInstance : MeasurableSpace (CausalTraj A O)) :=
  measurable_iff_comap_le.1 (measurable_causalPrefixMap t)

theorem causalPrefixSigma_mono : Monotone (causalPrefixSigma A O) := by
  intro s t hst
  unfold causalPrefixSigma
  rw [← causalTraceRestrict_comp_causalPrefixMap hst, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono
    (measurable_iff_comap_le.1 (measurable_causalTraceRestrict hst))

/-- The prefix map is measurable out of its own sigma-algebra. -/
theorem measurable_causalPrefixMap_prefixSigma (t : ℕ) :
    @Measurable (CausalTraj A O) (CausalFiniteTrace A O t)
      (causalPrefixSigma A O t) inferInstance (causalPrefixMap t) :=
  Measurable.of_comap_le le_rfl

/-- The prefix filtration on the causal path space. -/
def causalPrefixFiltration (A O : Type*) [Fintype A] [Fintype O]
    [MeasurableSpace A] [MeasurableSpace O]
    [MeasurableSingletonClass A] [MeasurableSingletonClass O] :
    Filtration ℕ (inferInstance : MeasurableSpace (CausalTraj A O)) where
  seq := causalPrefixSigma A O
  mono' := causalPrefixSigma_mono
  le' := causalPrefixSigma_le

theorem causalPrefixFiltration_apply (t : ℕ) :
    causalPrefixFiltration A O t = causalPrefixSigma A O t := rfl

/-- The prefix sigma-algebras generate the product sigma-algebra on paths. -/
theorem iSup_causalPrefixSigma :
    (⨆ t, causalPrefixSigma A O t) =
      (inferInstance : MeasurableSpace (CausalTraj A O)) := by
  apply le_antisymm
  · exact iSup_le fun t => causalPrefixSigma_le t
  · show (⨆ k : ℕ, MeasurableSpace.comap (fun ω : CausalTraj A O => ω k)
        (Prod.instMeasurableSpace : MeasurableSpace (A × O))) ≤ _
    refine iSup_le fun k => ?_
    have hfactor : (fun ω : CausalTraj A O => ω k) =
        (fun w : CausalFiniteTrace A O (k + 1) => w (Fin.last k)) ∘
          causalPrefixMap (k + 1) := by
      funext ω
      rfl
    rw [hfactor, ← MeasurableSpace.comap_comp]
    refine le_trans (MeasurableSpace.comap_mono
      (measurable_iff_comap_le.1 (measurable_pi_apply (Fin.last k)))) ?_
    exact le_iSup (causalPrefixSigma A O) (k + 1)

theorem iSup_causalPrefixFiltration :
    (⨆ t, causalPrefixFiltration A O t) =
      (inferInstance : MeasurableSpace (CausalTraj A O)) :=
  iSup_causalPrefixSigma

/-! ## The complete path experiment and its finite trace experiments -/

variable [Nonempty A] [Nonempty O]

/-- The complete path experiment `K_{π,∞}`: the causal path law of every world,
bundled as a finite measure on the path space. -/
noncomputable def causalPathExperiment (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) :
    Θ → FiniteMeasure (CausalTraj A O) :=
  fun θ => ⟨causalPathMeasure π.1 π.2 (Qs θ) (hQ θ), inferInstance⟩

theorem causalPathExperiment_coe (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (θ : Θ) :
    (causalPathExperiment Qs hQ π θ : Measure (CausalTraj A O)) =
      causalPathMeasure π.1 π.2 (Qs θ) (hQ θ) := rfl

instance isProbabilityMeasure_causalPathExperiment (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (θ : Θ) :
    IsProbabilityMeasure (causalPathExperiment Qs hQ π θ : Measure (CausalTraj A O)) := by
  rw [causalPathExperiment_coe]
  infer_instance

/-- The depth-`t` trace experiment `K_{π,t}` as a measure experiment: the
pushforward of the path law under the length-`t` prefix map. -/
noncomputable def causalTraceMeasureExperiment (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (t : ℕ) :
    Θ → FiniteMeasure (CausalFiniteTrace A O t) :=
  fun θ => ⟨Measure.map (causalPrefixMap t) (causalPathMeasure π.1 π.2 (Qs θ) (hQ θ)),
    inferInstance⟩

theorem causalTraceMeasureExperiment_coe (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (t : ℕ) (θ : Θ) :
    (causalTraceMeasureExperiment Qs hQ π t θ : Measure (CausalFiniteTrace A O t)) =
      Measure.map (causalPrefixMap t) (causalPathMeasure π.1 π.2 (Qs θ) (hQ θ)) := rfl

instance isProbabilityMeasure_causalTraceMeasureExperiment (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (t : ℕ) (θ : Θ) :
    IsProbabilityMeasure
      (causalTraceMeasureExperiment Qs hQ π t θ : Measure (CausalFiniteTrace A O t)) := by
  rw [causalTraceMeasureExperiment_coe]
  exact Measure.isProbabilityMeasure_map (measurable_causalPrefixMap t).aemeasurable

/-- The singleton masses of the trace measure experiment are exactly the
entries of the paper's finite trace experiment `causalFiniteExperiment`. -/
theorem causalTraceMeasureExperiment_singleton (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (t : ℕ) (θ : Θ)
    (w : CausalFiniteTrace A O t) :
    (causalTraceMeasureExperiment Qs hQ π t θ : Measure (CausalFiniteTrace A O t)) {w} =
      ENNReal.ofReal (causalFiniteExperiment π.1 Qs t θ w) := by
  rw [causalTraceMeasureExperiment_coe,
    Measure.map_apply (measurable_causalPrefixMap t) (measurableSet_singleton w),
    causalPrefixMap_preimage_singleton, causalPathMeasure_cyl]
  rfl

/-- The trace experiment is the deterministic prefix garbling of the complete
path experiment. -/
theorem causalTraceMeasureExperiment_eq_decode_path (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (t : ℕ) (θ : Θ) :
    causalTraceMeasureExperiment Qs hQ π t θ =
      finiteMarkovDecode
        ⟨Kernel.deterministic (causalPrefixMap t) (measurable_causalPrefixMap t),
          Kernel.isMarkovKernel_deterministic _⟩
        (causalPathExperiment Qs hQ π θ) := by
  apply Subtype.ext
  change Measure.map (causalPrefixMap t) (causalPathMeasure π.1 π.2 (Qs θ) (hQ θ)) =
    (Kernel.deterministic (causalPrefixMap t) (measurable_causalPrefixMap t)) ∘ₘ
      (causalPathMeasure π.1 π.2 (Qs θ) (hQ θ))
  rw [Measure.deterministic_comp_eq_map]

/-! ## Identification of the trimmed coarse experiment with the trace experiment -/

/-- The section is measurable into the prefix sigma-algebra (its domain is a
finite discrete space). -/
theorem measurable_causalTraceSection_prefixSigma (t : ℕ) :
    @Measurable (CausalFiniteTrace A O t) (CausalTraj A O)
      inferInstance (causalPrefixSigma A O t) (causalTraceSection t) := by
  intro s _
  exact (Set.toFinite _).measurableSet

/-- `section ∘ prefix` is measurable from the product sigma-algebra into the
prefix sigma-algebra. -/
theorem measurable_causalTraceSection_comp_prefixMap (t : ℕ) :
    @Measurable (CausalTraj A O) (CausalTraj A O)
      inferInstance (causalPrefixSigma A O t)
      (causalTraceSection t ∘ causalPrefixMap t) :=
  @Measurable.comp (CausalTraj A O) (CausalFiniteTrace A O t) (CausalTraj A O)
    inferInstance inferInstance (causalPrefixSigma A O t) _ _
    (measurable_causalTraceSection_prefixSigma t) (measurable_causalPrefixMap t)

theorem causalPrefixMap_comp_section_comp_prefixMap (t : ℕ) :
    causalPrefixMap t ∘ (causalTraceSection t ∘ causalPrefixMap (A := A) (O := O) t) =
      causalPrefixMap t := by
  rw [← Function.comp_assoc, causalPrefixMap_comp_causalTraceSection, Function.id_comp]

/-- **Coarse-sigma-algebra identification.** Trimming a path measure to the
prefix sigma-algebra is the same as pushing it forward along
`section ∘ prefix` into the coarse space. -/
theorem causalTrim_eq_map (μ : Measure (CausalTraj A O)) (t : ℕ) :
    μ.trim (causalPrefixSigma_le (A := A) (O := O) t) =
      @Measure.map (CausalTraj A O) (CausalTraj A O) inferInstance
        (causalPrefixSigma A O t) (causalTraceSection t ∘ causalPrefixMap t) μ := by
  apply @Measure.ext (CausalTraj A O) (causalPrefixSigma A O t)
  intro S hS
  rw [trim_measurableSet_eq _ hS,
    @Measure.map_apply (CausalTraj A O) (CausalTraj A O) inferInstance
      (causalPrefixSigma A O t) μ _ (measurable_causalTraceSection_comp_prefixMap t) S hS]
  obtain ⟨B, -, rfl⟩ := MeasurableSpace.measurableSet_comap.1 hS
  rw [← Set.preimage_comp, causalPrefixMap_comp_section_comp_prefixMap]

/-- The deterministic section kernel from the finite trace space into the
coarse path space. -/
noncomputable def causalSectionKernel (t : ℕ) :
    @FiniteMarkovKernel (CausalFiniteTrace A O t) (CausalTraj A O)
      inferInstance (causalPrefixSigma A O t) :=
  @FiniteMarkovKernel.mk (CausalFiniteTrace A O t) (CausalTraj A O)
    inferInstance (causalPrefixSigma A O t)
    (@Kernel.deterministic (CausalFiniteTrace A O t) (CausalTraj A O)
      inferInstance (causalPrefixSigma A O t) (causalTraceSection t)
      (measurable_causalTraceSection_prefixSigma t))
    (Kernel.isMarkovKernel_deterministic (measurable_causalTraceSection_prefixSigma t))

/-- The deterministic prefix kernel out of the coarse path space. -/
noncomputable def causalCoarsePrefixKernel (t : ℕ) :
    @FiniteMarkovKernel (CausalTraj A O) (CausalFiniteTrace A O t)
      (causalPrefixSigma A O t) inferInstance :=
  @FiniteMarkovKernel.mk (CausalTraj A O) (CausalFiniteTrace A O t)
    (causalPrefixSigma A O t) inferInstance
    (@Kernel.deterministic (CausalTraj A O) (CausalFiniteTrace A O t)
      (causalPrefixSigma A O t) inferInstance (causalPrefixMap t)
      (measurable_causalPrefixMap_prefixSigma t))
    (Kernel.isMarkovKernel_deterministic (measurable_causalPrefixMap_prefixSigma t))

/-- The trimmed coarse experiment is the deterministic section garbling of the
trace experiment. -/
theorem trimFinite_causalPath_eq_decode (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (t : ℕ) (θ : Θ) :
    trimFinite (causalPathExperiment Qs hQ π θ) (causalPrefixSigma_le t) =
      @finiteMarkovDecode (CausalFiniteTrace A O t) (CausalTraj A O)
        inferInstance (causalPrefixSigma A O t) (causalSectionKernel t)
        (causalTraceMeasureExperiment Qs hQ π t θ) := by
  apply Subtype.ext
  change (causalPathMeasure π.1 π.2 (Qs θ) (hQ θ)).trim (causalPrefixSigma_le t) =
    (@Kernel.deterministic (CausalFiniteTrace A O t) (CausalTraj A O)
        inferInstance (causalPrefixSigma A O t) (causalTraceSection t)
        (measurable_causalTraceSection_prefixSigma t)) ∘ₘ
      (Measure.map (causalPrefixMap t) (causalPathMeasure π.1 π.2 (Qs θ) (hQ θ)))
  rw [@Measure.deterministic_comp_eq_map (CausalFiniteTrace A O t) (CausalTraj A O)
      inferInstance (causalPrefixSigma A O t) _ _ (measurable_causalTraceSection_prefixSigma t),
    @Measure.map_map (CausalTraj A O) (CausalFiniteTrace A O t) (CausalTraj A O)
      inferInstance inferInstance (causalPrefixSigma A O t) _ _ _
      (measurable_causalTraceSection_prefixSigma t) (measurable_causalPrefixMap t),
    causalTrim_eq_map]

/-- The trace experiment is the deterministic prefix garbling of the trimmed
coarse experiment. -/
theorem causalTraceMeasureExperiment_eq_decode_trim (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (t : ℕ) (θ : Θ) :
    causalTraceMeasureExperiment Qs hQ π t θ =
      @finiteMarkovDecode (CausalTraj A O) (CausalFiniteTrace A O t)
        (causalPrefixSigma A O t) inferInstance (causalCoarsePrefixKernel t)
        (trimFinite (causalPathExperiment Qs hQ π θ) (causalPrefixSigma_le t)) := by
  apply Subtype.ext
  change Measure.map (causalPrefixMap t) (causalPathMeasure π.1 π.2 (Qs θ) (hQ θ)) =
    (@Kernel.deterministic (CausalTraj A O) (CausalFiniteTrace A O t)
        (causalPrefixSigma A O t) inferInstance (causalPrefixMap t)
        (measurable_causalPrefixMap_prefixSigma t)) ∘ₘ
      ((causalPathMeasure π.1 π.2 (Qs θ) (hQ θ)).trim (causalPrefixSigma_le t))
  rw [@Measure.deterministic_comp_eq_map (CausalTraj A O) (CausalFiniteTrace A O t)
      (causalPrefixSigma A O t) inferInstance _ _ (measurable_causalPrefixMap_prefixSigma t),
    causalTrim_eq_map,
    @Measure.map_map (CausalTraj A O) (CausalTraj A O) (CausalFiniteTrace A O t)
      inferInstance (causalPrefixSigma A O t) inferInstance _ _ _
      (measurable_causalPrefixMap_prefixSigma t)
      (measurable_causalTraceSection_comp_prefixMap t),
    causalPrefixMap_comp_section_comp_prefixMap]

/-! ## Encoding invariance of the measure deficiency (private helpers)

The general calculus for `finiteMeasureDeficiency` lives in
`MeasureDeficiency.lean`; the two facts used here are kept as private copies
so that this module depends only on `DominatedPrefix.lean`. -/

/-- **Encoding invariance.** The explicit finite trace experiment and the
trimmed coarse-sigma-algebra experiment are exact deterministic garblings of
each other, hence have the same directed deficiency to every target. -/
theorem finiteMeasureDeficiency_trace_eq_trim [Fintype Θ] [Nonempty Θ]
    {Y : Type*} [MeasurableSpace Y] [Nonempty Y]
    (Qs : Θ → CausalResponse A O) (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (π : ValidCausalPolicy A O) (t : ℕ) (F : Θ → FiniteMeasure Y) :
    finiteMeasureDeficiency (causalTraceMeasureExperiment Qs hQ π t) F =
      @finiteMeasureDeficiency Θ (CausalTraj A O) Y (causalPrefixSigma A O t) _
        (fun θ => trimFinite (causalPathExperiment Qs hQ π θ) (causalPrefixSigma_le t)) F := by
  apply @finiteMeasureDeficiency_eq_of_mutual_garbling
    Θ (CausalFiniteTrace A O t) Y inferInstance inferInstance inferInstance
    (CausalTraj A O) (causalPrefixSigma A O t)
    (causalTraceMeasureExperiment Qs hQ π t)
    (fun θ => trimFinite (causalPathExperiment Qs hQ π θ) (causalPrefixSigma_le t))
    (causalSectionKernel t) (fun θ => (trimFinite_causalPath_eq_decode Qs hQ π t θ).symm)
    (causalCoarsePrefixKernel t) (fun θ => (causalTraceMeasureExperiment_eq_decode_trim Qs hQ π t θ).symm)
    F
  · exact finiteMeasureDeficiencyCandidates_nonempty_of_fintype _ _
      ⟨Kernel.const _ (Measure.dirac (Classical.arbitrary Y)), inferInstance⟩
  · letI : MeasurableSpace (CausalTraj A O) := causalPrefixSigma A O t
    exact finiteMeasureDeficiencyCandidates_nonempty_of_fintype _ _
      ⟨Kernel.const _ (Measure.dirac (Classical.arbitrary Y)), inferInstance⟩

/-! ## Finite-class prefix continuity -/

section FiniteClass

variable [Fintype Θ] [Nonempty Θ]

/-- The dominating mixture `P̄ = ∑_θ P_θ` of the class path laws (unnormalized). -/
noncomputable def causalDominatingMixture (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) :
    Measure (CausalTraj A O) :=
  ∑ θ, causalPathMeasure π.1 π.2 (Qs θ) (hQ θ)

instance isFiniteMeasure_causalDominatingMixture (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) :
    IsFiniteMeasure (causalDominatingMixture Qs hQ π) := by
  unfold causalDominatingMixture
  infer_instance

theorem causalPathMeasure_le_causalDominatingMixture (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (θ : Θ) :
    causalPathMeasure π.1 π.2 (Qs θ) (hQ θ) ≤ causalDominatingMixture Qs hQ π :=
  Finset.single_le_sum (f := fun θ' => causalPathMeasure π.1 π.2 (Qs θ') (hQ θ'))
    (fun _ _ => bot_le) (Finset.mem_univ θ)

theorem causalPathMeasure_absolutelyContinuous_mixture (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (θ : Θ) :
    causalPathMeasure π.1 π.2 (Qs θ) (hQ θ) ≪ causalDominatingMixture Qs hQ π :=
  Measure.absolutelyContinuous_of_le (causalPathMeasure_le_causalDominatingMixture Qs hQ π θ)

/-- The Radon–Nikodym density `f_θ = dP_θ / dP̄` of the world-`θ` path law with
respect to the dominating mixture. -/
noncomputable def causalPathDensity (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (θ : Θ) :
    CausalTraj A O → ℝ :=
  fun ω => ((causalPathMeasure π.1 π.2 (Qs θ) (hQ θ)).rnDeriv
    (causalDominatingMixture Qs hQ π) ω).toReal

theorem stronglyMeasurable_causalPathDensity (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (θ : Θ) :
    StronglyMeasurable (causalPathDensity Qs hQ π θ) :=
  (Measure.measurable_rnDeriv _ _).ennreal_toReal.stronglyMeasurable

theorem integrable_causalPathDensity (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (θ : Θ) :
    Integrable (causalPathDensity Qs hQ π θ) (causalDominatingMixture Qs hQ π) :=
  Measure.integrable_toReal_rnDeriv

theorem causalPathDensity_nonneg (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (θ : Θ)
    (ω : CausalTraj A O) : 0 ≤ causalPathDensity Qs hQ π θ ω :=
  ENNReal.toReal_nonneg

/-- The path law of world `θ` has density `f_θ` with respect to the mixture. -/
theorem withDensity_causalPathDensity (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (θ : Θ) :
    (causalDominatingMixture Qs hQ π).withDensity
        (fun ω => ENNReal.ofReal (causalPathDensity Qs hQ π θ ω)) =
      causalPathMeasure π.1 π.2 (Qs θ) (hQ θ) := by
  conv_rhs => rw [← Measure.withDensity_rnDeriv_eq _ _
    (causalPathMeasure_absolutelyContinuous_mixture Qs hQ π θ)]
  apply withDensity_congr_ae
  filter_upwards [Measure.rnDeriv_ne_top (causalPathMeasure π.1 π.2 (Qs θ) (hQ θ))
    (causalDominatingMixture Qs hQ π)] with ω hω
  exact ENNReal.ofReal_toReal hω

theorem withDensityOfRealFinite_causalPathDensity (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (θ : Θ) :
    withDensityOfRealFinite (causalDominatingMixture Qs hQ π) (causalPathDensity Qs hQ π θ)
        (integrable_causalPathDensity Qs hQ π θ) =
      causalPathExperiment Qs hQ π θ :=
  Subtype.ext (withDensity_causalPathDensity Qs hQ π θ)

/-- A finite density family is relatively compact in `L¹(P̄)`. -/
theorem isCompact_closure_range_causalPathDensity (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) :
    IsCompact (closure (Set.range fun θ =>
      (integrable_causalPathDensity Qs hQ π θ).toL1 (causalPathDensity Qs hQ π θ))) :=
  (Set.finite_range _).isCompact_closure

/-- **Finite-class prefix continuity (trimmed form).** For a nonempty finite
class of valid causal response kernels and a valid policy, the directed
deficiency from the depth-`t` prefix experiment, encoded on the coarse
sigma-algebra `(Ω, ℱ_t)`, to the complete path experiment tends to zero. -/
theorem tendsto_causalTrimPrefixDeficiency (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) :
    Tendsto (fun t => @finiteMeasureDeficiency Θ (CausalTraj A O) (CausalTraj A O)
        (causalPrefixSigma A O t) inferInstance
        (fun θ => trimFinite (causalPathExperiment Qs hQ π θ) (causalPrefixSigma_le t))
        (causalPathExperiment Qs hQ π)) atTop (𝓝 0) := by
  have h := tendsto_dominatedPrefixDeficiency (causalDominatingMixture Qs hQ π)
    (causalPathDensity Qs hQ π) (stronglyMeasurable_causalPathDensity Qs hQ π)
    (integrable_causalPathDensity Qs hQ π) (causalPathDensity_nonneg Qs hQ π)
    (causalPrefixFiltration A O) iSup_causalPrefixFiltration
    (isCompact_closure_range_causalPathDensity Qs hQ π)
  refine h.congr fun t => ?_
  simp only [withDensityOfRealFinite_causalPathDensity]
  rfl

/-- The paper's displayed finite-class bound, trimmed form:
`δ(K_{π,t}, K_{π,∞}) ≤ (1/2) · max_θ ‖E[f_θ | ℱ_t] − f_θ‖_{L¹(P̄)}`. -/
theorem causalTrimPrefixDeficiency_le_half_max_L1 (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (t : ℕ) :
    @finiteMeasureDeficiency Θ (CausalTraj A O) (CausalTraj A O)
        (causalPrefixSigma A O t) inferInstance
        (fun θ => trimFinite (causalPathExperiment Qs hQ π θ) (causalPrefixSigma_le t))
        (causalPathExperiment Qs hQ π) ≤
      Finset.univ.sup' Finset.univ_nonempty (fun θ => (1 / 2) * ∫ ω,
        |(causalDominatingMixture Qs hQ π)[causalPathDensity Qs hQ π θ | causalPrefixSigma A O t] ω
          - causalPathDensity Qs hQ π θ ω| ∂(causalDominatingMixture Qs hQ π)) := by
  have h := dominatedPrefixDeficiency_le (causalDominatingMixture Qs hQ π)
    (causalPathDensity Qs hQ π) (stronglyMeasurable_causalPathDensity Qs hQ π)
    (integrable_causalPathDensity Qs hQ π) (causalPathDensity_nonneg Qs hQ π)
    (causalPrefixSigma A O t) (causalPrefixSigma_le t)
    (Finset.univ.sup' Finset.univ_nonempty (fun θ => (1 / 2) * ∫ ω,
      |(causalDominatingMixture Qs hQ π)[causalPathDensity Qs hQ π θ | causalPrefixSigma A O t] ω
        - causalPathDensity Qs hQ π θ ω| ∂(causalDominatingMixture Qs hQ π)))
    (fun θ => Finset.le_sup' (fun θ => (1 / 2) * ∫ ω,
      |(causalDominatingMixture Qs hQ π)[causalPathDensity Qs hQ π θ | causalPrefixSigma A O t] ω
        - causalPathDensity Qs hQ π θ ω| ∂(causalDominatingMixture Qs hQ π))
      (Finset.mem_univ θ))
  simpa only [withDensityOfRealFinite_causalPathDensity] using h

/-- **Finite-class prefix continuity (explicit trace form).** With the prefix
experiment encoded as the paper's finite trace experiment `K_{π,t}`
(pushforward under the prefix map), `δ(K_{π,t}, K_{π,∞}) → 0`. -/
theorem tendsto_causalPrefixDeficiency (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) :
    Tendsto (fun t => finiteMeasureDeficiency (causalTraceMeasureExperiment Qs hQ π t)
      (causalPathExperiment Qs hQ π)) atTop (𝓝 0) := by
  refine (tendsto_causalTrimPrefixDeficiency Qs hQ π).congr fun t => ?_
  exact (finiteMeasureDeficiency_trace_eq_trim Qs hQ π t _).symm

/-- The displayed finite-class bound in explicit trace form. -/
theorem causalPrefixDeficiency_le_half_max_L1 (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ)) (π : ValidCausalPolicy A O) (t : ℕ) :
    finiteMeasureDeficiency (causalTraceMeasureExperiment Qs hQ π t)
        (causalPathExperiment Qs hQ π) ≤
      Finset.univ.sup' Finset.univ_nonempty (fun θ => (1 / 2) * ∫ ω,
        |(causalDominatingMixture Qs hQ π)[causalPathDensity Qs hQ π θ | causalPrefixSigma A O t] ω
          - causalPathDensity Qs hQ π θ ω| ∂(causalDominatingMixture Qs hQ π)) := by
  rw [finiteMeasureDeficiency_trace_eq_trim]
  exact causalTrimPrefixDeficiency_le_half_max_L1 Qs hQ π t

end FiniteClass

end IdExp
