import Formal.CausalBehavior

/-!
# Unnormalized controlled-prefix behaviors

`CausalBehavior` is normalized at the empty history.  Rerooting a behavior at
an arbitrary prefix should not invent a conditional law at a null event, so it
cannot be a total operation with values again in `CausalBehavior`.

The quotient-safe total operation instead lands in `CausalSubbehavior`: the
cone of globally consistent, nonnegative controlled-prefix mass families, with
no root normalization. Operational shifts of a normalized behavior occupy its
root-at-most-one slice. Shifting by `pre` simply reads the original joint masses at
`pre ++ rest`.  A null prefix therefore gives the zero subbehavior.  At a
positive-mass prefix, dividing by the shifted root gives the normalized
reachable continuation behavior.
-/

namespace IdExp

open Finset

set_option linter.unusedSectionVars false

variable {A O : Type*} [Fintype A] [Fintype O]

/-- A nonnegative, globally consistent controlled-prefix mass family with no
root normalization. It is the positive cone generated by controlled behaviors,
not one probability distribution over action--observation histories. -/
structure CausalSubbehavior (A O : Type*) [Fintype O] where
  /-- Joint controlled mass of a finite action--observation history. -/
  mass : CausalHistory A O → ℝ
  /-- All controlled masses are nonnegative. -/
  nonneg : ∀ h, 0 ≤ mass h
  /-- For each fixed next action, summing its observation children recovers
  the parent mass. -/
  consistent : ∀ (h : CausalHistory A O) (a : A),
    ∑ o, mass (h ++ [(a, o)]) = mass h

namespace CausalSubbehavior

@[ext]
theorem ext {p q : CausalSubbehavior A O} (h : p.mass = q.mass) : p = q := by
  cases p
  cases q
  cases h
  rfl

/-- The identically zero controlled-mass family. -/
protected def zero : CausalSubbehavior A O where
  mass := fun _ => 0
  nonneg := fun _ => le_rfl
  consistent := by simp

instance : Zero (CausalSubbehavior A O) := ⟨CausalSubbehavior.zero⟩

@[simp]
theorem zero_mass (h : CausalHistory A O) :
    (0 : CausalSubbehavior A O).mass h = 0 :=
  rfl

/-- A one-step extension has no more mass than its parent. -/
theorem child_le (p : CausalSubbehavior A O) (h : CausalHistory A O)
    (a : A) (o : O) : p.mass (h ++ [(a, o)]) ≤ p.mass h := by
  rw [← p.consistent h a]
  exact Finset.single_le_sum
    (fun y _ => p.nonneg (h ++ [(a, y)])) (Finset.mem_univ o)

/-- Every controlled-prefix mass is at most the subbehavior's root mass. -/
theorem mass_le_root (p : CausalSubbehavior A O) (h : CausalHistory A O) :
    p.mass h ≤ p.mass [] := by
  induction h using List.reverseRecOn with
  | nil => exact le_rfl
  | append_singleton h ao ih => exact (p.child_le h ao.1 ao.2).trans ih

/-- Every child of a null controlled prefix is null. -/
theorem child_eq_zero_of_eq_zero (p : CausalSubbehavior A O)
    (h : CausalHistory A O) (a : A) (o : O) (hh : p.mass h = 0) :
    p.mass (h ++ [(a, o)]) = 0 := by
  apply le_antisymm
  · simpa [hh] using p.child_le h a o
  · exact p.nonneg _

/-- Every descendant of a null controlled prefix is null. -/
theorem mass_append_eq_zero_of_eq_zero (p : CausalSubbehavior A O)
    (pre rest : CausalHistory A O) (hpre : p.mass pre = 0) :
    p.mass (pre ++ rest) = 0 := by
  induction rest using List.reverseRecOn with
  | nil => simpa using hpre
  | append_singleton rest ao ih =>
      simpa only [List.append_assoc] using
        p.child_eq_zero_of_eq_zero (pre ++ rest) ao.1 ao.2 ih

/-- A subbehavior with null root is identically zero. -/
theorem eq_zero_of_mass_nil_eq_zero (p : CausalSubbehavior A O)
    (hroot : p.mass [] = 0) : p = 0 := by
  apply CausalSubbehavior.ext
  funext h
  simpa using p.mass_append_eq_zero_of_eq_zero [] h hroot

/-- Total prefix shift.  Unlike raw-kernel rerooting, this uses joint masses
and is therefore meaningful at both reachable and null prefixes. -/
def shift (p : CausalSubbehavior A O) (pre : CausalHistory A O) :
    CausalSubbehavior A O where
  mass := fun rest => p.mass (pre ++ rest)
  nonneg := fun rest => p.nonneg (pre ++ rest)
  consistent := by
    intro rest a
    simpa only [List.append_assoc] using p.consistent (pre ++ rest) a

@[simp]
theorem shift_mass (p : CausalSubbehavior A O) (pre rest : CausalHistory A O) :
    (p.shift pre).mass rest = p.mass (pre ++ rest) :=
  rfl

/-- The root of a shifted subbehavior is exactly the original prefix mass. -/
@[simp]
theorem shift_mass_nil (p : CausalSubbehavior A O) (pre : CausalHistory A O) :
    (p.shift pre).mass [] = p.mass pre := by
  simp [shift]

/-- Appending any continuation cannot increase controlled mass. -/
theorem mass_append_le (p : CausalSubbehavior A O)
    (pre rest : CausalHistory A O) : p.mass (pre ++ rest) ≤ p.mass pre := by
  simpa using (p.shift pre).mass_le_root rest

@[simp]
theorem shift_nil (p : CausalSubbehavior A O) : p.shift [] = p := by
  apply CausalSubbehavior.ext
  funext h
  rfl

/-- Successive shifts concatenate their prefixes. -/
theorem shift_shift (p : CausalSubbehavior A O) (pre rest : CausalHistory A O) :
    (p.shift pre).shift rest = p.shift (pre ++ rest) := by
  apply CausalSubbehavior.ext
  funext h
  simp only [shift_mass, List.append_assoc]

/-- Shifting at a null prefix yields the zero subbehavior, not an arbitrary
normalized continuation. -/
theorem shift_eq_zero_of_mass_eq_zero (p : CausalSubbehavior A O)
    (pre : CausalHistory A O) (hpre : p.mass pre = 0) :
    p.shift pre = 0 := by
  apply CausalSubbehavior.ext
  funext rest
  simp only [shift_mass, zero_mass]
  exact p.mass_append_eq_zero_of_eq_zero pre rest hpre

/-- Normalize a positive-root subbehavior to a causal behavior. -/
noncomputable def normalize (p : CausalSubbehavior A O)
    (hroot : 0 < p.mass []) : CausalBehavior A O where
  mass := fun h => p.mass h / p.mass []
  root := div_self hroot.ne'
  nonneg := fun h => div_nonneg (p.nonneg h) hroot.le
  consistent := by
    intro h a
    rw [← Finset.sum_div, p.consistent h a]

@[simp]
theorem normalize_mass (p : CausalSubbehavior A O)
    (hroot : 0 < p.mass []) (h : CausalHistory A O) :
    (p.normalize hroot).mass h = p.mass h / p.mass [] :=
  rfl

/-- Every positive-root subbehavior is exactly its root mass times its
normalized behavior, coordinate by coordinate. -/
theorem mass_eq_root_mul_normalize_mass (p : CausalSubbehavior A O)
    (hroot : 0 < p.mass []) (h : CausalHistory A O) :
    p.mass h = p.mass [] * (p.normalize hroot).mass h := by
  rw [normalize_mass]
  field_simp

end CausalSubbehavior

namespace CausalBehavior

/-- Regard a normalized behavior as an unnormalized subbehavior of root mass
one. -/
def toSubbehavior (p : CausalBehavior A O) : CausalSubbehavior A O where
  mass := p.mass
  nonneg := p.nonneg
  consistent := p.consistent

@[simp]
theorem toSubbehavior_mass (p : CausalBehavior A O) (h : CausalHistory A O) :
    p.toSubbehavior.mass h = p.mass h :=
  rfl

@[simp]
theorem toSubbehavior_mass_nil (p : CausalBehavior A O) :
    p.toSubbehavior.mass [] = 1 :=
  p.root

/-- The normalized-to-unnormalized map is an embedding of the behavioral
world space into root-one subbehaviors. -/
theorem toSubbehavior_injective :
    Function.Injective (toSubbehavior : CausalBehavior A O → CausalSubbehavior A O) := by
  intro p q hpq
  apply CausalBehavior.ext
  exact congrArg CausalSubbehavior.mass hpq

/-- Normalizing an embedded behavior recovers it exactly. -/
@[simp]
theorem normalize_toSubbehavior (p : CausalBehavior A O) :
    p.toSubbehavior.normalize (by simp [p.root]) = p := by
  apply CausalBehavior.ext
  funext h
  simp [CausalSubbehavior.normalize, p.root]

/-- The quotient-safe unnormalized continuation at an arbitrary prefix. -/
def prefixSubbehavior (p : CausalBehavior A O) (pre : CausalHistory A O) :
    CausalSubbehavior A O :=
  p.toSubbehavior.shift pre

@[simp]
theorem prefixSubbehavior_mass (p : CausalBehavior A O)
    (pre rest : CausalHistory A O) :
    (p.prefixSubbehavior pre).mass rest = p.mass (pre ++ rest) :=
  rfl

/-- Its root is the probability of the prefix itself. -/
@[simp]
theorem prefixSubbehavior_mass_nil (p : CausalBehavior A O)
    (pre : CausalHistory A O) :
    (p.prefixSubbehavior pre).mass [] = p.mass pre := by
  simp [prefixSubbehavior]

/-- Although the ambient subbehavior cone is unnormalized, every prefix shift
of a normalized behavior has root mass at most one. -/
theorem prefixSubbehavior_root_le_one (p : CausalBehavior A O)
    (pre : CausalHistory A O) :
    (p.prefixSubbehavior pre).mass [] ≤ 1 := by
  rw [prefixSubbehavior_mass_nil]
  exact p.mass_le_one pre

/-- A null prefix has the zero unnormalized continuation. -/
theorem prefixSubbehavior_eq_zero_of_mass_eq_zero (p : CausalBehavior A O)
    (pre : CausalHistory A O) (hpre : p.mass pre = 0) :
    p.prefixSubbehavior pre = 0 :=
  p.toSubbehavior.shift_eq_zero_of_mass_eq_zero pre hpre

/-- The normalized continuation at a reachable controlled prefix. -/
noncomputable def reachableContinuation (p : CausalBehavior A O)
    (pre : CausalHistory A O) (hpre : 0 < p.mass pre) : CausalBehavior A O :=
  (p.prefixSubbehavior pre).normalize (by simpa using hpre)

/-- Reachable continuation is exactly conditional joint mass divided by the
prefix mass. -/
@[simp]
theorem reachableContinuation_mass (p : CausalBehavior A O)
    (pre : CausalHistory A O) (hpre : 0 < p.mass pre)
    (rest : CausalHistory A O) :
    (p.reachableContinuation pre hpre).mass rest =
      p.mass (pre ++ rest) / p.mass pre := by
  change (p.prefixSubbehavior pre).mass rest /
      (p.prefixSubbehavior pre).mass [] = _
  rw [prefixSubbehavior_mass, prefixSubbehavior_mass_nil]

/-- Reachable continuation gives the exact multiplicative factorization of a
joint controlled mass into its prefix mass and conditional continuation mass. -/
theorem reachableContinuation_factorization (p : CausalBehavior A O)
    (pre : CausalHistory A O) (hpre : 0 < p.mass pre)
    (rest : CausalHistory A O) :
    p.mass (pre ++ rest) =
      p.mass pre * (p.reachableContinuation pre hpre).mass rest := by
  rw [reachableContinuation_mass]
  field_simp

/-- Positive mass of a descendant forces positive mass of its prefix. -/
theorem mass_pos_of_append_pos (p : CausalBehavior A O)
    (pre rest : CausalHistory A O)
    (happend : 0 < p.mass (pre ++ rest)) : 0 < p.mass pre := by
  exact happend.trans_le (by simpa using p.toSubbehavior.mass_append_le pre rest)

/-- A positive joint continuation has positive normalized continuation mass. -/
theorem reachableContinuation_mass_pos (p : CausalBehavior A O)
    (pre : CausalHistory A O) (hpre : 0 < p.mass pre)
    (rest : CausalHistory A O)
    (happend : 0 < p.mass (pre ++ rest)) :
    0 < (p.reachableContinuation pre hpre).mass rest := by
  rw [reachableContinuation_mass]
  exact div_pos happend hpre

/-- Normalizing after two successive reachable prefixes is the same as
normalizing once after their concatenation. -/
theorem reachableContinuation_comp (p : CausalBehavior A O)
    (pre rest : CausalHistory A O)
    (happend : 0 < p.mass (pre ++ rest)) :
    let hpre := p.mass_pos_of_append_pos pre rest happend
    let hrest := p.reachableContinuation_mass_pos pre hpre rest happend
    (p.reachableContinuation pre hpre).reachableContinuation rest hrest =
      p.reachableContinuation (pre ++ rest) happend := by
  dsimp only
  apply CausalBehavior.ext
  funext tail
  simp only [reachableContinuation_mass]
  field_simp [List.append_assoc]
  rw [mul_div_cancel_right₀ _
    (ne_of_gt (p.mass_pos_of_append_pos pre rest happend))]
  simp only [List.append_assoc]

end CausalBehavior

end IdExp
