import Formal.CausalBehaviorExperiment

/-!
# Observation-only finite causal plans

The reader paper writes a deterministic depth-`n` intervention as a tree whose
next action is a function only of the preceding observations.  The older Lean
type `CausalPlan A O n` accepts complete action-observation histories.  Those
extra action coordinates are redundant on trajectories generated by the plan,
but the two types were not previously connected by a literal theorem.

This module supplies the observation-tree type and proves that it generates
exactly the same native experiments.  It does not change the existing plan
type or any paper definition.
-/

namespace IdExp

set_option linter.unusedSectionVars false

universe u v

/-- A deterministic finite intervention in the observation-tree form used in
the paper: choose a root action, then one observation-tree continuation for
each possible first observation. -/
def CausalObservationPlan (A : Type u) (O : Type v) : ℕ → Type (max u v)
  | 0 => PUnit
  | n + 1 => A × (O → CausalObservationPlan A O n)

namespace CausalObservationPlan

variable {A O Θ : Type*} [Fintype A] [Fintype O]

noncomputable instance instFintype : ∀ n, Fintype (CausalObservationPlan A O n)
  | 0 => by
      change Fintype PUnit
      infer_instance
  | n + 1 => by
      letI : Fintype (CausalObservationPlan A O n) := instFintype n
      change Fintype (A × (O → CausalObservationPlan A O n))
      classical
      exact Fintype.ofFinite _

instance instNonempty [Nonempty A] : ∀ n, Nonempty (CausalObservationPlan A O n)
  | 0 => by
      change Nonempty PUnit
      infer_instance
  | n + 1 => by
      letI : Nonempty (CausalObservationPlan A O n) := instNonempty n
      change Nonempty (A × (O → CausalObservationPlan A O n))
      infer_instance

/-- Forget that a plan was presented as an observation tree and view it as a
full-history plan.  Past action coordinates are ignored by construction. -/
def toCausalPlanAux : ∀ n, CausalObservationPlan A O n → CausalPlan A O n
  | 0, _ => fun x => Fin.elim0 x.1
  | n + 1, σ =>
      CausalPlan.cons σ.1 (fun o => toCausalPlanAux n (σ.2 o))

def toCausalPlan {n : ℕ} (σ : CausalObservationPlan A O n) : CausalPlan A O n :=
  toCausalPlanAux n σ

/-- Remove the redundant off-trajectory action branches of a full-history
plan, retaining its root and recursively retaining only the continuation
following that root action and each possible observation. -/
noncomputable def ofCausalPlanAux : ∀ n, CausalPlan A O n → CausalObservationPlan A O n
  | 0, _ => PUnit.unit
  | n + 1, τ =>
      (τ.root, fun o => ofCausalPlanAux n (τ.after o))

noncomputable def ofCausalPlan {n : ℕ} (τ : CausalPlan A O n) :
    CausalObservationPlan A O n :=
  ofCausalPlanAux n τ

@[simp]
theorem ofCausalPlan_toCausalPlan : ∀ n (σ : CausalObservationPlan A O n),
    ofCausalPlan (toCausalPlan σ) = σ := by
  intro n
  induction n with
  | zero =>
      intro σ
      rcases σ with ⟨⟩
      rfl
  | succ n ih =>
      intro σ
      rcases σ with ⟨a, next⟩
      apply Prod.ext
      · rfl
      · funext o
        exact ih (next o)

/-- Canonicalizing a full-history plan through its observation tree preserves
the reconstructed full trace for every observation word. -/
theorem trace_toCausalPlan_ofCausalPlan : ∀ n (τ : CausalPlan A O n)
    (y : CausalObservationTrace O n),
    causalTraceOfObservations (toCausalPlan (ofCausalPlan τ)) y =
      causalTraceOfObservations τ y := by
  intro n
  induction n with
  | zero =>
      intro τ y
      funext i
      exact Fin.elim0 i
  | succ n ih =>
      intro τ y
      rw [causalTraceOfObservations_succ, causalTraceOfObservations_succ]
      simp only [toCausalPlan, ofCausalPlan, toCausalPlanAux, ofCausalPlanAux,
        CausalPlan.cons_root, CausalPlan.cons_after]
      congr 1
      simpa only [toCausalPlan, ofCausalPlan] using
        ih (τ.after (y 0)) (Fin.tail y)

/-- Native plan evaluation written directly on a controlled-prefix behavior
and an observation-only plan. -/
noncomputable def behaviorPlanLaw {n : ℕ} (σ : CausalObservationPlan A O n)
    (p : CausalBehavior A O) : CausalObservationTrace O n → ℝ :=
  causalBehaviorPlanLaw n σ.toCausalPlan p

theorem behaviorPlanLaw_isDist {n : ℕ} (σ : CausalObservationPlan A O n)
    (p : CausalBehavior A O) : IsDist (behaviorPlanLaw σ p) :=
  causalBehaviorPlanLaw_isDist n σ.toCausalPlan p

/-- The finite experiment associated with an observation-only native plan. -/
noncomputable def behaviorPlanExperiment {n : ℕ}
    (σ : CausalObservationPlan A O n) (ps : Θ → CausalBehavior A O) :
    FiniteExperiment Θ (CausalObservationTrace O n) :=
  fun θ => behaviorPlanLaw σ (ps θ)

theorem behaviorPlanExperiment_valid {n : ℕ}
    (σ : CausalObservationPlan A O n) (ps : Θ → CausalBehavior A O) :
    IsFiniteExperiment (behaviorPlanExperiment σ ps) :=
  fun θ => behaviorPlanLaw_isDist σ (ps θ)

/-- Every full-history plan has exactly the same direct native experiment as
its observation-only canonicalization. -/
theorem behaviorPlanExperiment_ofCausalPlan {n : ℕ}
    (τ : CausalPlan A O n) (ps : Θ → CausalBehavior A O) :
    behaviorPlanExperiment (ofCausalPlan τ) ps =
      causalBehaviorPlanExperiment n τ ps := by
  funext θ y
  unfold behaviorPlanExperiment behaviorPlanLaw causalBehaviorPlanExperiment
  simp only [causalBehaviorPlanLaw_apply]
  rw [trace_toCausalPlan_ofCausalPlan]

/-- Conversely, every observation-only plan is already represented by its
embedded full-history plan.  Together with
`behaviorPlanExperiment_ofCausalPlan`, this proves equality of the two native
experiment families, even though the underlying plan types are not claimed
to be equivalent as raw functions. -/
theorem behaviorPlanExperiment_toCausalPlan {n : ℕ}
    (σ : CausalObservationPlan A O n) (ps : Θ → CausalBehavior A O) :
    behaviorPlanExperiment σ ps =
      causalBehaviorPlanExperiment n σ.toCausalPlan ps :=
  rfl

end CausalObservationPlan

end IdExp
