import Formal.SilentAfterHorizon
import Formal.BoundedApproachCertificate
import Formal.FinitePolicyPerturbation

/-!
# Compactness and attainment for silent finite-horizon classes

This module formalizes T10(2) from
`TheoryDocs/approach_case_synthesis.tex`.  Under the literal common-silent
suffix assumption of `SilentAfterHorizon.lean`, every limiting policy
profile depends only on the finitely many behavioral rows before the silent
horizon.  Those rows form a compact product of simplices.

The only analytic point needing care for an arbitrary (possibly infinite)
world class is continuity of deficiency uniformly over worlds.  We obtain it
from the existing policy-trace telescope and the one-Lipschitz source
perturbation theorem for finite deficiency, rather than assuming finiteness
of the world class.
-/

namespace IdExp

open Finset Set

noncomputable section

set_option linter.unusedSectionVars false

variable {A O Θ : Type*} [Fintype A] [Fintype O]
  [Nonempty A] [Nonempty O] [Nonempty Θ]

/-! ## The compact finite policy-row polytope -/

/-- The product of action simplices indexed by causal decision histories
strictly before `H`. -/
abbrev SilentHorizonPolicyRows (A O : Type*) [Fintype A] (H : ℕ) :=
  stochasticRules (CausalDecisionPoint A O H) A

/-- A point of the finite policy-row polytope supplies one valid action
distribution at every bounded decision history. -/
theorem silentHorizonPolicyRows_isDist
    {H : ℕ} (x : SilentHorizonPolicyRows A O H)
    (d : CausalDecisionPoint A O H) :
    IsDist (x.1 d) :=
  x.2 d (Set.mem_univ d)

/-- Extend the bounded policy rows by the repository's fixed default tail. -/
def silentHorizonPolicyOfRows (H : ℕ)
    (x : SilentHorizonPolicyRows A O H) : ValidCausalPolicy A O :=
  boundedCausalPolicy H x.1 (silentHorizonPolicyRows_isDist x)

/-- Restrict an arbitrary valid policy to its rows before `H`. -/
def silentHorizonRowsOfPolicy (H : ℕ) (π : ValidCausalPolicy A O) :
    SilentHorizonPolicyRows A O H :=
  ⟨fun d => π.1 (causalDecisionHistory d),
    fun d _ => π.2 (causalDecisionHistory d)⟩

noncomputable instance silentHorizonPolicyRows_compactSpace (H : ℕ) :
    CompactSpace (SilentHorizonPolicyRows A O H) :=
  isCompact_iff_compactSpace.mp
    (isCompact_stochasticRules (CausalDecisionPoint A O H) A)

/-! ## Uniform continuity of the finite-horizon deficiency coordinates -/

/-- Row total variation is bounded by the ambient sup distance on the finite
policy table. -/
theorem finiteTV_silentHorizonPolicyRows_le_dist
    {H : ℕ} (x y : SilentHorizonPolicyRows A O H)
    (d : CausalDecisionPoint A O H) :
    finiteTV (x.1 d) (y.1 d) ≤
      ((Fintype.card A : ℝ) / 2) * dist x y := by
  have hcoord (a : A) : |x.1 d a - y.1 d a| ≤ dist x y := by
    rw [← Real.dist_eq]
    calc
      dist (x.1 d a) (y.1 d a) ≤ dist (x.1 d) (y.1 d) :=
        ((dist_pi_le_iff dist_nonneg).1 le_rfl) a
      _ ≤ dist x.1 y.1 :=
        ((dist_pi_le_iff dist_nonneg).1 le_rfl) d
      _ = dist x y := by rw [Subtype.dist_eq]
  unfold finiteTV
  calc
    (1 / 2 : ℝ) * ∑ a, |x.1 d a - y.1 d a| ≤
        (1 / 2 : ℝ) * ∑ _a : A, dist x y := by
      gcongr with a
      exact hcoord a
    _ = ((Fintype.card A : ℝ) / 2) * dist x y := by
      simp
      ring

/-- The complete recorded horizon-`H` experiments generated by two finite
policy tables are uniformly close over every response world. -/
theorem finiteTV_silentHorizonPolicyOfRows_experiment_le
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (H : ℕ) (x y : SilentHorizonPolicyRows A O H) (θ : Θ) :
    finiteTV
        (causalFiniteExperiment (silentHorizonPolicyOfRows H x).1 Qs H θ)
        (causalFiniteExperiment (silentHorizonPolicyOfRows H y).1 Qs H θ) ≤
      (H : ℝ) * (((Fintype.card A : ℝ) / 2) * dist x y) := by
  let c : ℝ := ((Fintype.card A : ℝ) / 2) * dist x y
  have hc0 : 0 ≤ c := mul_nonneg (by positivity) dist_nonneg
  have hlocal : ∀ k (u : CausalFiniteTrace A O k),
      finiteTV
          ((silentHorizonPolicyOfRows H x).1 (List.ofFn u))
          ((silentHorizonPolicyOfRows H y).1 (List.ofFn u)) ≤ c := by
    intro k u
    by_cases hk : k < H
    · simpa [c, silentHorizonPolicyOfRows, boundedCausalPolicy, hk] using
        (finiteTV_silentHorizonPolicyRows_le_dist x y
          (causalDecisionPointOfHistory H (List.ofFn u) (by simpa using hk)))
    · simpa [silentHorizonPolicyOfRows, boundedCausalPolicy, hk, finiteTV] using hc0
  have htv := causalFiniteExperiment_policy_tv_le_sum
    (silentHorizonPolicyOfRows H x).1
    (silentHorizonPolicyOfRows H y).1
    (silentHorizonPolicyOfRows H x).2
    (silentHorizonPolicyOfRows H y).2
    (Qs θ) (hQ θ) (fun _ => c) hlocal H
  change finiteTV
      (causalFiniteExperiment (silentHorizonPolicyOfRows H x).1
        (fun _ : Unit => Qs θ) H ())
      (causalFiniteExperiment (silentHorizonPolicyOfRows H y).1
        (fun _ : Unit => Qs θ) H ()) ≤ _ at htv
  have hxunit :
      causalFiniteExperiment (silentHorizonPolicyOfRows H x).1 Qs H θ =
        causalFiniteExperiment (silentHorizonPolicyOfRows H x).1
          (fun _ : Unit => Qs θ) H () := by
    rfl
  have hyunit :
      causalFiniteExperiment (silentHorizonPolicyOfRows H y).1 Qs H θ =
        causalFiniteExperiment (silentHorizonPolicyOfRows H y).1
          (fun _ : Unit => Qs θ) H () := by
    rfl
  calc
    finiteTV
        (causalFiniteExperiment (silentHorizonPolicyOfRows H x).1 Qs H θ)
        (causalFiniteExperiment (silentHorizonPolicyOfRows H y).1 Qs H θ) ≤
        ∑ _k ∈ Finset.range H, c := by
      rw [hxunit, hyunit]
      simpa using htv
    _ = (H : ℝ) * c := by simp
    _ = (H : ℝ) * (((Fintype.card A : ℝ) / 2) * dist x y) := rfl

/-- A reusable Lipschitz bound for every fixed finite target.  It is valid
for an arbitrary nonempty world class. -/
theorem abs_finiteDeficiency_silentHorizonPolicyOfRows_sub_le
    {Y : Type*} [Fintype Y] [Nonempty Y]
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (H : ℕ) (F : FiniteExperiment Θ Y) (hF : IsFiniteExperiment F)
    (x y : SilentHorizonPolicyRows A O H) :
    |finiteDeficiency
          (causalFiniteExperiment (silentHorizonPolicyOfRows H x).1 Qs H) F -
        finiteDeficiency
          (causalFiniteExperiment (silentHorizonPolicyOfRows H y).1 Qs H) F| ≤
      (H : ℝ) * (((Fintype.card A : ℝ) / 2) * dist x y) := by
  exact abs_finiteDeficiency_sub_le_of_rowTV
    (causalFiniteExperiment (silentHorizonPolicyOfRows H x).1 Qs H)
    (causalFiniteExperiment (silentHorizonPolicyOfRows H y).1 Qs H)
    F
    (causalFiniteExperiment_valid _ (silentHorizonPolicyOfRows H x).2 Qs hQ H)
    (causalFiniteExperiment_valid _ (silentHorizonPolicyOfRows H y).2 Qs hQ H)
    hF _
    (finiteTV_silentHorizonPolicyOfRows_experiment_le Qs hQ H x y)

/-- Deficiency to a fixed finite target is continuous on the bounded
policy-row polytope, uniformly over an arbitrary response-world class. -/
theorem continuous_finiteDeficiency_silentHorizonPolicyOfRows
    {Y : Type*} [Fintype Y] [Nonempty Y]
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (H : ℕ) (F : FiniteExperiment Θ Y) (hF : IsFiniteExperiment F) :
    Continuous (fun x : SilentHorizonPolicyRows A O H =>
      finiteDeficiency
        (causalFiniteExperiment (silentHorizonPolicyOfRows H x).1 Qs H) F) := by
  rw [Metric.continuous_iff]
  intro x ε hε
  let C : ℝ := (H : ℝ) * ((Fintype.card A : ℝ) / 2)
  have hC0 : 0 ≤ C := mul_nonneg (by positivity) (by positivity)
  let δ : ℝ := ε / (C + 1)
  have hδ : 0 < δ := div_pos hε (by linarith)
  refine ⟨δ, hδ, ?_⟩
  intro y hy
  have hlip :=
    abs_finiteDeficiency_silentHorizonPolicyOfRows_sub_le
      Qs hQ H F hF y x
  have hscale :
      C * dist y x < ε := by
    calc
      C * dist y x ≤ (C + 1) * dist y x := by
        exact mul_le_mul_of_nonneg_right (by linarith) dist_nonneg
      _ < (C + 1) * δ :=
        mul_lt_mul_of_pos_left hy (by linarith)
      _ = ε := by
        dsimp [δ]
        field_simp
  rw [Real.dist_eq]
  have hlip' :
      |finiteDeficiency
          (causalFiniteExperiment (silentHorizonPolicyOfRows H y).1 Qs H) F -
        finiteDeficiency
          (causalFiniteExperiment (silentHorizonPolicyOfRows H x).1 Qs H) F| ≤
        C * dist y x := by
    simpa [C, mul_assoc] using hlip
  exact hlip'.trans_lt hscale

/-! ## Continuous profile factorization and compact raw range -/

/-- The stabilized profile generated by one finite policy table. -/
def silentHorizonProfileMap
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O)
    (H : ℕ) (x : SilentHorizonPolicyRows A O H) : ProfileCube :=
  causalPolicyProfile Qs hQ e (silentHorizonPolicyOfRows H x)

/-- Under silence, the finite-table profile map is continuous into the
product profile cube. -/
theorem continuous_silentHorizonProfileMap
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O)
    (H : ℕ) (oStar : O)
    (hsilent : CausalSilentAfterHorizon Qs H oStar) :
    Continuous (silentHorizonProfileMap Qs hQ e H) := by
  apply continuous_pi
  intro j
  apply Continuous.subtype_mk
  convert continuous_finiteDeficiency_silentHorizonPolicyOfRows
    Qs hQ H (causalNativeTestExperiment Qs (e j))
      (causalNativeTestExperiment_valid Qs hQ (e j)) using 1
  funext x
  exact causalPolicyProfileValue_silentAfterHorizon_eq
    (silentHorizonPolicyOfRows H x) Qs hQ e H oStar hsilent j

/-- Extending the finite restriction of a policy by the default tail
preserves its entire stabilized profile. -/
theorem silentHorizonProfileMap_rowsOfPolicy
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O)
    (H : ℕ) (oStar : O)
    (hsilent : CausalSilentAfterHorizon Qs H oStar)
    (π : ValidCausalPolicy A O) :
    silentHorizonProfileMap Qs hQ e H
        (silentHorizonRowsOfPolicy H π) =
      causalPolicyProfile Qs hQ e π := by
  funext j
  apply Subtype.ext
  change causalPolicyProfileValue
      (silentHorizonPolicyOfRows H (silentHorizonRowsOfPolicy H π)) Qs e j =
    causalPolicyProfileValue π Qs e j
  rw [causalPolicyProfileValue_silentAfterHorizon_eq
      (silentHorizonPolicyOfRows H (silentHorizonRowsOfPolicy H π))
      Qs hQ e H oStar hsilent j,
    causalPolicyProfileValue_silentAfterHorizon_eq
      π Qs hQ e H oStar hsilent j]
  unfold causalPolicyTestDeficiency
  congr 1
  unfold silentHorizonPolicyOfRows
  rw [causalFiniteExperiment_boundedCausalPolicy]
  simpa [silentHorizonRowsOfPolicy] using
    (causalFiniteExperiment_eq_boundedCausalTraceMass Qs π H).symm

/-- The raw profile set is exactly the range of the compact finite-table
profile map. -/
theorem causalPolicyProfiles_eq_range_silentHorizonProfileMap
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O)
    (H : ℕ) (oStar : O)
    (hsilent : CausalSilentAfterHorizon Qs H oStar) :
    causalPolicyProfiles Qs hQ e =
      Set.range (silentHorizonProfileMap Qs hQ e H) := by
  ext p
  constructor
  · rintro ⟨π, rfl⟩
    exact ⟨silentHorizonRowsOfPolicy H π,
      silentHorizonProfileMap_rowsOfPolicy
        Qs hQ e H oStar hsilent π⟩
  · rintro ⟨x, rfl⟩
    exact ⟨silentHorizonPolicyOfRows H x, rfl⟩

/-- T10(2a): the raw attainable profile set is compact. -/
theorem causalPolicyProfiles_isCompact_of_silentAfterHorizon
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O)
    (H : ℕ) (oStar : O)
    (hsilent : CausalSilentAfterHorizon Qs H oStar) :
    IsCompact (causalPolicyProfiles Qs hQ e) := by
  rw [causalPolicyProfiles_eq_range_silentHorizonProfileMap
    Qs hQ e H oStar hsilent]
  exact isCompact_range
    (continuous_silentHorizonProfileMap Qs hQ e H oStar hsilent)

/-- T10(2b): completion adds no new profiles in a silent finite-horizon
class. -/
theorem causalProfileClosure_eq_policyProfiles_of_silentAfterHorizon
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O)
    (H : ℕ) (oStar : O)
    (hsilent : CausalSilentAfterHorizon Qs H oStar) :
    causalProfileClosure Qs hQ e = causalPolicyProfiles Qs hQ e :=
  (causalPolicyProfiles_isCompact_of_silentAfterHorizon
    Qs hQ e H oStar hsilent).isClosed.closure_eq

/-- T10(2c): every point on the completed Pareto frontier is the profile of
one valid causal policy. -/
theorem causalParetoFrontier_point_attained_of_silentAfterHorizon
    (Qs : Θ → CausalResponse A O)
    (hQ : ∀ θ, IsCausalResponse (Qs θ))
    (e : ℕ ≃ CausalNativeTest A O)
    (H : ℕ) (oStar : O)
    (hsilent : CausalSilentAfterHorizon Qs H oStar)
    (p : ProfileCube) (hp : p ∈ causalParetoFrontier Qs hQ e) :
    ∃ π : ValidCausalPolicy A O,
      causalPolicyProfile Qs hQ e π = p := by
  have hpRaw : p ∈ causalPolicyProfiles Qs hQ e := by
    rw [← causalProfileClosure_eq_policyProfiles_of_silentAfterHorizon
      Qs hQ e H oStar hsilent]
    exact hp.1
  exact hpRaw

end

end IdExp
