import Formal.UnattainedNonzeroFrontier

/-!
# Canonical finite stopping experiment for the hidden wait/proxy class

This module isolates the finite experiment generated by the world-independent
first-test stopping law of a policy.  `WaitProxyCausalTrace.lean` proves that
this canonical statistic is Blackwell-equivalent to the complete finite
recorded causal trace.
-/

namespace IdExp

open Finset Topology

noncomputable section

variable {A : Type*} [Fintype A] [DecidableEq A] [Nonempty A]

/-- At horizon `n`, either no test occurred or the signal records its first
test depth, coordinate, and returned proxy bit. -/
abbrev WaitProxyStoppingSignal (A : Type*) (n : ℕ) :=
  Option (Fin n × A × Bool)

/-- The finite experiment determined by the first-test masses of `π`.
The no-test atom has the surviving mass; a test atom carries the appropriate
binary-symmetric response. -/
def waitProxyStoppingExperiment
    (π : CausalPolicy (WaitProxyAction A) WaitProxyObservation)
    (c : ℕ → ℝ) (n : ℕ) :
    FiniteExperiment (A → Bool) (WaitProxyStoppingSignal A n) :=
  fun θ sig =>
    match sig with
    | none => waitProxySurvival π n
    | some (s, a, b) =>
        waitProxyFirstTestMass π s.1 a *
          (if b = θ a then 1 / 2 + c s.1 else 1 / 2 - c s.1)

theorem waitProxyStoppingExperiment_valid
    (π : CausalPolicy (WaitProxyAction A) WaitProxyObservation)
    (hπ : IsCausalPolicy π) (c : ℕ → ℝ)
    (hc0 : ∀ s, 0 ≤ c s) (hchalf : ∀ s, c s ≤ 1 / 2) (n : ℕ) :
    IsFiniteExperiment (waitProxyStoppingExperiment π c n) := by
  intro θ
  constructor
  · intro sig
    cases sig with
    | none =>
        exact waitProxySurvival_nonneg π hπ n
    | some sab =>
        rcases sab with ⟨s, a, b⟩
        exact mul_nonneg (waitProxyFirstTestMass_nonneg π hπ s.1 a)
          (by split_ifs <;> linarith [hc0 s.1, hchalf s.1])
  · rw [Fintype.sum_option, Fintype.sum_prod_type]
    simp_rw [Fintype.sum_prod_type]
    simp only [waitProxyStoppingExperiment]
    have hbit (s : Fin n) (a : A) :
        ∑ b : Bool, (if b = θ a then 1 / 2 + c s.1 else 1 / 2 - c s.1) = 1 := by
      cases θ a <;> simp <;> ring
    simp_rw [← Finset.mul_sum, hbit, mul_one]
    have hsum :
        (∑ s : Fin n, ∑ a, waitProxyFirstTestMass π s.1 a) =
          ∑ s ∈ Finset.range n, ∑ a, waitProxyFirstTestMass π s a := by
      simpa using Fin.sum_univ_eq_sum_range
        (fun s => ∑ a, waitProxyFirstTestMass π s a) n
    rw [hsum]
    linarith [sum_waitProxyFirstTestMass_add_survival π hπ n]

/-- A branchwise BSC decoder: only tests of coordinate `a` are retained;
all other atoms, including no test, are mapped to a fair bit. -/
def waitProxyStoppingDecoder (a : A) (d : ℝ) :
    WaitProxyStoppingSignal A n → Bool → ℝ :=
  fun sig o =>
    match sig with
    | none => 1 / 2
    | some (_s, b, x) =>
        if b = a then
          if o = x then 1 / 2 + d else 1 / 2 - d
        else 1 / 2

omit [Fintype A] [Nonempty A] in
theorem waitProxyStoppingDecoder_valid (a : A) {d : ℝ}
    (hd0 : 0 ≤ d) (hdhalf : d ≤ 1 / 2) :
    waitProxyStoppingDecoder (n := n) a d ∈
      stochasticRules (WaitProxyStoppingSignal A n) Bool := by
  intro sig _
  constructor
  · intro o
    cases sig with
    | none => simp [waitProxyStoppingDecoder]
    | some sbx =>
        rcases sbx with ⟨s, b, x⟩
        simp only [waitProxyStoppingDecoder]
        split_ifs <;> linarith
  · cases sig with
    | none => simp [waitProxyStoppingDecoder]
    | some sbx =>
        rcases sbx with ⟨s, b, x⟩
        by_cases hba : b = a
        · cases x <;> simp [waitProxyStoppingDecoder, hba] <;> ring
        · simp [waitProxyStoppingDecoder, hba]
/-- Composing two centered binary-symmetric channels multiplies their signed
strengths by two. -/
theorem sum_waitProxy_bsc_comp (c d : ℝ) (x o : Bool) :
    ∑ b : Bool,
      (if b = x then 1 / 2 + c else 1 / 2 - c) *
        (if o = b then 1 / 2 + d else 1 / 2 - d) =
      if o = x then 1 / 2 + 2 * c * d else 1 / 2 - 2 * c * d := by
  rw [Fintype.sum_bool]
  cases x <;> cases o <;> simp <;> ring

/-- Forgetting a centered binary-symmetric signal produces a fair bit. -/
theorem sum_waitProxy_bsc_fair (c : ℝ) (x : Bool) :
    ∑ b : Bool,
      (if b = x then 1 / 2 + c else 1 / 2 - c) * (1 / 2) = 1 / 2 := by
  rw [Fintype.sum_bool]
  cases x <;> simp <;> ring

/-- The canonical stopping decoder produces a centered binary experiment whose
strength is the finite effective coordinate weight times the decoder strength. -/
theorem waitProxyStoppingDecoder_law
    (π : CausalPolicy (WaitProxyAction A) WaitProxyObservation)
    (hπ : IsCausalPolicy π) (c : ℕ → ℝ)
    (_hc0 : ∀ s, 0 ≤ c s) (_hchalf : ∀ s, c s ≤ 1 / 2)
    (n : ℕ) (a : A) (d : ℝ) (θ : A → Bool) (o : Bool) :
    finiteDecisionLaw (waitProxyStoppingExperiment π c n)
        (waitProxyStoppingDecoder (n := n) a d) θ o =
      if o = θ a then
        1 / 2 + waitProxyEffectiveWeightFinite π c n a * d
      else
        1 / 2 - waitProxyEffectiveWeightFinite π c n a * d := by
  unfold finiteDecisionLaw
  rw [Fintype.sum_option, Fintype.sum_prod_type]
  simp_rw [Fintype.sum_prod_type]
  simp only [waitProxyStoppingExperiment, waitProxyStoppingDecoder]
  have hbranch (s : Fin n) (b : A) :
      ∑ x : Bool,
        (waitProxyFirstTestMass π s.1 b *
          (if x = θ b then 1 / 2 + c s.1 else 1 / 2 - c s.1)) *
          (if b = a then
            if o = x then 1 / 2 + d else 1 / 2 - d
          else 1 / 2) =
        waitProxyFirstTestMass π s.1 b *
          (if b = a then
            if o = θ a then 1 / 2 + 2 * c s.1 * d
            else 1 / 2 - 2 * c s.1 * d
          else 1 / 2) := by
    by_cases hba : b = a
    · subst b
      simp only [if_true]
      simp_rw [mul_assoc]
      rw [← Finset.mul_sum, sum_waitProxy_bsc_comp]
      by_cases hoa : o = θ a <;>
        simp only [hoa, if_true, if_false] <;> ring
    · simp only [hba, if_false]
      simp_rw [mul_assoc]
      rw [← Finset.mul_sum, sum_waitProxy_bsc_fair]
  simp_rw [hbranch]
  have hcoord (s : Fin n) :
      ∑ b : A, waitProxyFirstTestMass π s.1 b *
          (if b = a then
            if o = θ a then 1 / 2 + 2 * c s.1 * d
            else 1 / 2 - 2 * c s.1 * d
          else 1 / 2) =
        waitProxyFirstTestTotal π s.1 / 2 +
          if o = θ a then
            2 * waitProxyFirstTestMass π s.1 a * c s.1 * d
          else
            -(2 * waitProxyFirstTestMass π s.1 a * c s.1 * d) := by
    let r : A → ℝ := fun b => waitProxyFirstTestMass π s.1 b
    let q : ℝ :=
      if o = θ a then 1 / 2 + 2 * c s.1 * d
      else 1 / 2 - 2 * c s.1 * d
    calc
      ∑ b : A, r b * (if b = a then q else 1 / 2) =
          ∑ b : A, (r b / 2 + if b = a then r b * (q - 1 / 2) else 0) := by
            apply Finset.sum_congr rfl
            intro b _
            by_cases hba : b = a <;> simp [hba] <;> ring
      _ = (∑ b : A, r b) / 2 + r a * (q - 1 / 2) := by
            rw [Finset.sum_add_distrib, ← Finset.sum_div]
            rw [Finset.sum_ite_eq' Finset.univ a]
            simp
      _ = waitProxyFirstTestTotal π s.1 / 2 +
          if o = θ a then
            2 * waitProxyFirstTestMass π s.1 a * c s.1 * d
          else
            -(2 * waitProxyFirstTestMass π s.1 a * c s.1 * d) := by
            unfold r q waitProxyFirstTestTotal
            by_cases hoa : o = θ a <;> simp [hoa] <;> ring
  simp_rw [hcoord]
  have hmass :
      waitProxySurvival π n +
          ∑ s : Fin n, waitProxyFirstTestTotal π s.1 = 1 := by
    have hsum :
        (∑ s : Fin n, waitProxyFirstTestTotal π s.1) =
          ∑ s ∈ Finset.range n, waitProxyFirstTestTotal π s := by
      simpa using Fin.sum_univ_eq_sum_range
        (fun s => waitProxyFirstTestTotal π s) n
    rw [hsum]
    have htel := sum_waitProxyFirstTestMass_add_survival π hπ n
    simp only [waitProxyFirstTestTotal] at htel ⊢
    linarith
  have heff :
      ∑ s : Fin n, 2 * waitProxyFirstTestMass π s.1 a * c s.1 =
        waitProxyEffectiveWeightFinite π c n a := by
    have hsum :
        (∑ s : Fin n, 2 * waitProxyFirstTestMass π s.1 a * c s.1) =
          ∑ s ∈ Finset.range n, 2 * waitProxyFirstTestMass π s a * c s := by
      simpa using Fin.sum_univ_eq_sum_range
        (fun s => 2 * waitProxyFirstTestMass π s a * c s) n
    rw [hsum]
    unfold waitProxyEffectiveWeightFinite
    simp_rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro s _
    ring
  by_cases hoa : o = θ a
  · simp only [hoa, if_true]
    rw [Finset.sum_add_distrib, ← Finset.sum_div]
    have hweighted :
        ∑ s : Fin n,
            2 * waitProxyFirstTestMass π s.1 a * c s.1 * d =
          waitProxyEffectiveWeightFinite π c n a * d := by
      rw [← Finset.sum_mul, heff]
    rw [hweighted]
    linarith
  · simp only [hoa, if_false]
    rw [Finset.sum_add_distrib, ← Finset.sum_div, Finset.sum_neg_distrib]
    have hweighted :
        ∑ s : Fin n,
            2 * waitProxyFirstTestMass π s.1 a * c s.1 * d =
          waitProxyEffectiveWeightFinite π c n a * d := by
      rw [← Finset.sum_mul, heff]
    rw [hweighted]
    linarith

/-- The two worlds differing only at coordinate `a` are separated by exactly
the finite effective weight assigned to that coordinate. -/
theorem waitProxyStopping_pair_tv
    (π : CausalPolicy (WaitProxyAction A) WaitProxyObservation)
    (hπ : IsCausalPolicy π) (c : ℕ → ℝ)
    (hc0 : ∀ s, 0 ≤ c s) (_hchalf : ∀ s, c s ≤ 1 / 2)
    (n : ℕ) (a : A) :
    finiteTV
        (waitProxyStoppingExperiment π c n zeroWorld)
        (waitProxyStoppingExperiment π c n (flipWorld a)) =
      waitProxyEffectiveWeightFinite π c n a := by
  unfold finiteTV
  rw [Fintype.sum_option, Fintype.sum_prod_type]
  simp_rw [Fintype.sum_prod_type]
  simp only [waitProxyStoppingExperiment]
  have hbranch (s : Fin n) (b : A) :
      ∑ x : Bool,
        |waitProxyFirstTestMass π s.1 b *
            (if x = zeroWorld b then 1 / 2 + c s.1 else 1 / 2 - c s.1) -
          waitProxyFirstTestMass π s.1 b *
            (if x = flipWorld a b then 1 / 2 + c s.1 else 1 / 2 - c s.1)| =
        if b = a then
          4 * waitProxyFirstTestMass π s.1 b * c s.1
        else 0 := by
    by_cases hba : b = a
    · subst b
      rw [Fintype.sum_bool]
      have hr := waitProxyFirstTestMass_nonneg π hπ s.1 a
      have hc := hc0 s.1
      simp only [zeroWorld, flipWorld, decide_true, if_true]
      simp only [Bool.true_eq_false, Bool.false_eq_true, if_false]
      rw [abs_of_nonpos (by nlinarith), abs_of_nonneg (by nlinarith)]
      ring
    · simp [zeroWorld, flipWorld, hba]
  simp_rw [hbranch]
  simp only [sub_self, abs_zero, zero_add]
  simp_rw [Finset.sum_ite_eq' Finset.univ a]
  simp only [Finset.mem_univ, if_true]
  have hsum :
      (∑ s : Fin n,
          4 * waitProxyFirstTestMass π s.1 a * c s.1) =
        ∑ s ∈ Finset.range n,
          4 * waitProxyFirstTestMass π s a * c s := by
    simpa using Fin.sum_univ_eq_sum_range
      (fun s => 4 * waitProxyFirstTestMass π s a * c s) n
  rw [hsum]
  unfold waitProxyEffectiveWeightFinite
  simp_rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro s _
  ring

/-- The explicit branchwise decoder has worst-world error equal to the
positive or negative strength mismatch. -/
theorem waitProxyStoppingDecoder_error
    (π : CausalPolicy (WaitProxyAction A) WaitProxyObservation)
    (hπ : IsCausalPolicy π) (c : ℕ → ℝ)
    (hc0 : ∀ s, 0 ≤ c s) (hchalf : ∀ s, c s ≤ 1 / 2)
    (n : ℕ) (a : A) (targetStrength d : ℝ) (θ : A → Bool) :
    decodeErr (waitProxyStoppingExperiment π c n)
        (waitProxyTarget targetStrength a)
        (waitProxyStoppingDecoder (n := n) a d) θ =
      |targetStrength - waitProxyEffectiveWeightFinite π c n a * d| := by
  change (1 / 2 : ℝ) * ∑ o : Bool,
    |finiteDecisionLaw (waitProxyStoppingExperiment π c n)
        (waitProxyStoppingDecoder (n := n) a d) θ o -
      waitProxyTarget targetStrength a θ o| = _
  rw [Fintype.sum_bool]
  simp only [waitProxyStoppingDecoder_law π hπ c hc0 hchalf n a d]
  cases hθ : θ a <;> simp [waitProxyTarget, hθ] <;>
    rw [abs_sub_comm
      (waitProxyEffectiveWeightFinite π c n a * d) targetStrength] <;>
    ring

/-- **Exact finite stopping-coordinate deficiency.**  Optimizing the canonical
first-test experiment against a noisy coordinate target yields precisely the
same positive-part profile formula as in the paper. -/
theorem waitProxyStopping_deficiency
    (π : CausalPolicy (WaitProxyAction A) WaitProxyObservation)
    (hπ : IsCausalPolicy π) (c : ℕ → ℝ)
    (hc0 : ∀ s, 0 ≤ c s) (hchalf : ∀ s, c s ≤ 1 / 2)
    (n : ℕ) {targetStrength : ℝ}
    (ht0 : 0 ≤ targetStrength) (hthalf : targetStrength ≤ 1 / 2)
    (a : A) :
    finiteDeficiency (waitProxyStoppingExperiment π c n)
        (waitProxyTarget targetStrength a) =
      max (targetStrength -
        waitProxyEffectiveWeightFinite π c n a / 2) 0 := by
  let w := waitProxyEffectiveWeightFinite π c n a
  have hw0 : 0 ≤ w :=
    waitProxyEffectiveWeightFinite_nonneg π hπ c hc0 n a
  obtain ⟨d, hd0, hdhalf, hd⟩ :=
    exists_waitProxy_decoder_strength hw0 ht0 hthalf
  apply le_antisymm
  · exact finiteDeficiency_le_of_decoder _ _
      (waitProxyStoppingDecoder (n := n) a d)
      (waitProxyStoppingDecoder_valid a hd0 hdhalf) _
      (fun θ =>
        (waitProxyStoppingDecoder_error π hπ c hc0 hchalf n a
          targetStrength d θ).trans (by simpa [w] using hd) |>.le)
  · apply le_csInf (finiteDeficiencyCandidates_nonempty_of_valid _ _
      (waitProxyStoppingExperiment_valid π hπ c hc0 hchalf n)
      (waitProxyTarget_valid ht0 hthalf a))
    rintro q ⟨G, hG, herr⟩
    have hpair := finiteTV_pairwise_decoder_lower
      (waitProxyStoppingExperiment π c n)
      (waitProxyTarget targetStrength a) G hG
      zeroWorld (flipWorld a) q (herr zeroWorld) (herr (flipWorld a))
    rw [waitProxyTarget_pair_tv ht0 a,
      waitProxyStopping_pair_tv π hπ c hc0 hchalf n a] at hpair
    have hq0 : 0 ≤ q :=
      (decodeErr_nonneg (waitProxyStoppingExperiment π c n)
        (waitProxyTarget targetStrength a) G zeroWorld).trans
        (herr zeroWorld)
    rcases le_total (w / 2) targetStrength with hwt | htw
    · rw [max_eq_left (sub_nonneg.2 hwt)]
      dsimp [w] at hpair ⊢
      linarith
    · rw [max_eq_right (sub_nonpos.2 htw)]
      exact hq0

/-- Finite canonical stopping deficiencies converge coordinatewise to the
algebraic infinite effective-weight profile. -/
theorem tendsto_waitProxyStopping_deficiency
    (π : CausalPolicy (WaitProxyAction A) WaitProxyObservation)
    (hπ : IsCausalPolicy π) (c : ℕ → ℝ)
    (hc0 : ∀ s, 0 ≤ c s) (hchalf : ∀ s, c s ≤ 1 / 2)
    {targetStrength : ℝ}
    (ht0 : 0 ≤ targetStrength) (hthalf : targetStrength ≤ 1 / 2)
    (a : A) :
    Filter.Tendsto
      (fun n => finiteDeficiency (waitProxyStoppingExperiment π c n)
        (waitProxyTarget targetStrength a))
      Filter.atTop
      (𝓝 (max (targetStrength -
        waitProxyEffectiveWeight π c a / 2) 0)) := by
  have hw := waitProxyEffectiveWeightFinite_tendsto
    π hπ c hc0 hchalf a
  have ht : Filter.Tendsto (fun _ : ℕ => targetStrength)
      Filter.atTop (𝓝 targetStrength) :=
    tendsto_const_nhds
  have hz : Filter.Tendsto (fun _ : ℕ => (0 : ℝ))
      Filter.atTop (𝓝 0) :=
    tendsto_const_nhds
  have hlim := (ht.sub (hw.div_const 2)).max hz
  simpa only [waitProxyStopping_deficiency π hπ c hc0 hchalf
    _ ht0 hthalf a] using hlim


end

end IdExp
